### ISSUE TITLE
Flaky test: OpenTelemetry.Instrumentation.Grpc.Tests.GrpcTests.GrpcAspNetCoreInstrumentationAddsCorrectAttributes

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet#1082]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1073/checks?check_run_id=986181718#step:6:324

```terminal
  X OpenTelemetry.Instrumentation.Grpc.Tests.GrpcTests.GrpcAspNetCoreInstrumentationAddsCorrectAttributes [227ms]
  Error Message:
   Assert.Equal() Failure
Expected: 2
Actual:   4
  Stack Trace:
     at OpenTelemetry.Instrumentation.Grpc.Tests.GrpcTests.GrpcAspNetCoreInstrumentationAddsCorrectAttributes() in D:\a\opentelemetry-dotnet\opentelemetry-dotnet\test\OpenTelemetry.Instrumentation.Grpc.Tests\GrpcTests.server.cs:line 53
```

**Comment by alanwest** [comment]
Doh! I battled these tests a bit when putting them in place. I think I know what the cause is here...

When:
1. multiple instrumentation test suites are run concurrently, and
2. the test suites use the same instrumentation, then
3. the test suites can conflict with one another since they are run in the same testhost process

I originally had this problem between the gRPC client and server tests because both of them use the HttpClient instrumentation behind the scenes. I solved this by combining the [client](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs#L28) and [server](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.server.cs#L30) test suites into a partial class. One class means there is only one test suite and the individual tests in the suite do not run concurrently.

I had noted that we do the same thing with some HttpClient tests [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.server.cs#L30) and [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.netcore31.cs#L34). So, I followed that pattern.

My guess is that in (perhaps the more rare chance) the gRPC test suite may run at the same time as the HttpClient test suite and cause this problem.

In XUnit the [Collection](https://xunit.net/docs/running-tests-in-parallel.html#parallelism-in-test-frameworks) attribute is supposed to help. Though, if I recall, this worked for me locally, but it did not work with the CI.

**Comment by alanwest** [comment]
There were definitely issues with this test originally, though I'm pretty sure we haven't seen this flicker for some time now.
