### ISSUE TITLE
XML comment analysis is disabled for Linux/MacOS

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-dotnet#110]
See https://github.com/open-telemetry/opentelemetry-dotnet/pull/88/checks?check_run_id=149915175 build for an example - specifically it seems like the following StyleCop rules are checked on Windows and not on Linux/macOS

* SA1602 - `Enumeration items should be documented`
* SA1506 - `Element documentation headers should not be followed by blank line`
* SA1648 - `inheritdoc should be used with inheriting class`

**Comment by bruno-garcia** [comment]
I believe this issue was addressed this via #208 by removing the `OS == Windows_NT` from `GenerateDocumentationFile`.

In fact, a search for `Windows_NT` results in checks only for the tests projects, not to run `net4x` outside of Windows, which would require Mono installed:

https://github.com/open-telemetry/opentelemetry-dotnet/search?q=Windows_NT&unscoped_q=Windows_NT

See #155 for details.
