### ISSUE TITLE
Tags API clean-up

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#117]
Tag's new name is distributed context. Needs renaming

**Comment by SergeyKanzhelev** [comment]
see spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/distributedcontext-api.md

**Comment by lmolkova** [comment]
In the scope of this issue we should also consider
- removing builders - this came from Java and builders are not good in .NET because of allocations
- consider using structs instead of classes
- System.Diagnostics.Activity.Baggage is for Distributed Context - can we support it with Activity.Baggage (likely not)?

**Comment by austinlparker** [comment]
There's a distributed context proposal working through the spec group.

**Comment by SergeyKanzhelev** [comment]
What needs to be done as a minimal cleanup: 
1. TagKey, TagValue -> replace with simple strings (#320)
2. Create tagger factory
3. Rename tags to DistributedContext
4. Add metadata with TTL (#33)

**Comment by SergeyKanzhelev** [comment]
This is tracked in OTEM-66 item assigned to @MikeGoldsmith
