### ISSUE TITLE
Instrumentation Filter possible confusion with return type.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1186]
PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/1181 exposed public Filter to Http/Aspnet instrumentations.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationOptions.cs#L43

There are some possible confusion point about the Filter.
The Filter is expected to return a bool now, with true indicating "Yes,I want to collect this request", and No indicating "No i dont want the request".

One alternate proposal is to change bool to an Enum like: CollectRequest, FilterRequest to make this less confusing.

Opening this issue to continue exploring alternates and continue the discussion from the PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/1181#discussion_r478647545

**Comment by kevinmckinley** [comment]
The general notion of what a filter _is_ is complicated. Does it define what is permitted or what is removed?

Personally I am in favor of Filter returning bool to define what is allowed. While dotnet uses `Where()` to return matching subsets, `Filter()` is commonly used in this way by other languages (See @reyang's note https://github.com/open-telemetry/opentelemetry-dotnet/pull/1181#discussion_r478844006) and [Javascript](https://www.w3schools.com/jsref/jsref_filter.asp), [Ruby](https://apidock.com/ruby/Array/filter), and [Python](https://www.w3schools.com/python/ref_func_filter.asp)

The [inline docs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationOptions.cs#L31) describe intent well:
```
...
/// If Filter returns true, the request is collected.
/// If Filter returns false or throw exception, the request is filtered out.
...
```
However, I see that there is opportunity for confusion in the `Advanced Configuration` section of the README. The use of "filter _out_" seems to misrepresents the intent. 

Perhaps rewording this sentence to focus on "allowed" instead of "rejected" could help?
Here is one proposal to flip the description:
Current: `"This can be used to filter out any requests based on some condition."`
Proposal: `"This defines the condition for allowable requests."` or `"This defines the criteria for desired requests."`

Additionally, the example code could also be changed to focus on the desired condition.
For example:
```csharp
services.AddOpenTelemetryTracing(
        (builder) => builder
        .AddAspNetCoreInstrumentation(
            opt => opt.Filter =
                (httpContext) =>
                {
                    // only instrument HTTP GET requests
                    return httpContext.Request.Method.Equals("GET");
                })
        .AddJaegerExporter()
        );
```

**Comment by kevinmckinley** [comment]
Now that I've made the case, above, for Filter() returning bool for allowed... 
Here's another suggestion:
Rename or split the method into two. `Include()` or `Exclude()` or `Reject()`. These remove ambiguity and could additionally allow the implementation to handle exceptions during evaluation differently.

Example for `Exclude()`:
```csharp
services.AddOpenTelemetryTracing(
        (builder) => builder
            .AddAspNetCoreInstrumentation(
                opt => opt.Exclude =
                    (httpContext) => httpContext.Request.Method.Equals("POST")
            )
        .AddJaegerExporter()
        );
```

**Comment by cijothomas** [comment]
> Perhaps rewording this sentence to focus on "allowed" instead of "rejected" could help?
> Here is one proposal to flip the description:
> Current: "This can be used to filter out any requests based on some condition."
> Proposal: "This defines the condition for allowable requests." or "This defines the criteria for desired requests."

These sound good improvement.

**Comment by kevinmckinley** [comment]
@cijothomas Should the inline summary description for AspNetInstrumentationOptions.Filter also be updated to say "...to collect telemetry about requests..." instead of "...to filter instrumentation for requests..."?

https://github.com/open-telemetry/opentelemetry-dotnet/blob/7c9bee3f6d92d1f768802be7953079b82bf58cd2/src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationOptions.cs#L29

**Comment by cijothomas** [comment]
> @cijothomas Should the inline summary description for AspNetInstrumentationOptions.Filter also be updated to say "...to collect telemetry about requests..." instead of "...to filter instrumentation for requests..."?
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/7c9bee3f6d92d1f768802be7953079b82bf58cd2/src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationOptions.cs#L29

Yes lets make it all consistent!
