### ISSUE TITLE
Enrich callback not invoked when using dotnet framework

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-dotnet#1473]
# Bug Report

Enrich callback isn't called for sql activities when using dotnet framework

Enrich was added to the dotnet core implementation

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs#L94

But not the dotnet framework one

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs#L84

**Comment by cijothomas** [comment]
As .NET Framework does not publish any additional payload, there is nothing we can use to Enrich.... Must document this, if not already documented..

**Comment by chris-smith-zocdoc** [comment]
> As .NET Framework does not publish any additional payload, there is nothing we can use to Enrich.... Must document this, if not already documented..

Its true I'm not sure if there's anything useful to pass into Enrich. I was using it as a callback to grab some external state (async locals + stacktrace) to add to the activity. So its useful in that sense. As a work around I'm using an activity processor instead

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/1481 Doc issue will be tracked here.

**Comment by cijothomas** [comment]
> > As .NET Framework does not publish any additional payload, there is nothing we can use to Enrich.... Must document this, if not already documented..
> 
> Its true I'm not sure if there's anything useful to pass into Enrich. I was using it as a callback to grab some external state (async locals + stacktrace) to add to the activity. So its useful in that sense. As a work around I'm using an activity processor instead

Enrich has specific purpose - you want to add something to activity based on some information not readily available in processor. For adding anything in general to activity, activity processor is the spec-recommended approach.

**Comment by zfael** [comment]
@cijothomas @chris-smith-zocdoc I've been facing the same problem described in this Issue: 
- Enrich not being triggered for .NET Framework 4.5.2

Wanted to check if that's possible to trigger somehow or it's not supported at all for .NET Framework 4.5.2

## **Context** 
I was relying on `Enrich` method to be able to access the HTTP Request/Response objects in order to check and use the headers and bodies for each one of those.
So not having that triggered kinda break what I have so far which works on .NET Core, and I also want to get that working on a .NET Framework side of things

Regarding this: `As .NET Framework does not publish any additional payload`. We would be able to access HTTP objects if we could Enrich this instrumentation, wouldn't we? if so I see value in here it being triggered, don't you think?

To wrap this up, I've also looked into the Processors but I dont see a way I could access HTTP objects in there, do you guys have any tips on that?

Looking forward to your answers in here, and really appreciate any help 👍
