### ISSUE TITLE
Auto-collectors create scope and never dispose it

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#163]
Auto-collector based on DiagnosticSource receives different events for starting/stopping activity.
Now they all start span in start and end it in stop event. 

Between start and stop state is preserved through AsyncLocal Activity object.

IScope does not work well with this approach. On one side, we have to create it to make Span current (and preserve it to be available in stop), on the other side, there is no way to dispose it.

So we'll need to allow auto-collectors work without creating Scope objects.

**Comment by austinlparker** [comment]
Is there some sort of storage available for DiagnosticSource that could hold the span reference?

**Comment by lmolkova** [comment]
There is in ConcurrentSpanUtils - but span reference is hold (attached to Activity) only after someone calls WithSpan. Which creates IScope

**Comment by austinlparker** [comment]
Oh, hrm. There ought to be a way to create a span without a scope, I believe.

**Comment by lmolkova** [comment]
yes, we create span, but we don't make it scoped by default

**Comment by pcwiese** [comment]
Is the only method of attaching a Span to the current Activity via WithSpan? That method always returns a scope that when disposed with mark the Span as finished. Is there a way to attach a span to an Activity without that behavior?

I ask because OpenTracing allows that it seems. There is an Activate method that takes a Boolean finishOnDispose flag. There doesn't appear to be any way to pass a false value down with the current OpenTelemetry public API.

**Comment by lmolkova** [comment]
there is no way to attach span to the activity except WithSpan. Activity is .NET concept and we are working with .NET folks to help us define the right way to integrate Spans with Activities.

this is issue of how to propagate current span between start/stop events rather than how to stop span and while it is possible today, it is not a clean solution that we cannot dispose scopes.
