### ISSUE TITLE
AddOtlpExporter in Asp net core application breaks the pipelines

### ISSUE THREAD

**Issue by evilpilaf** [open-telemetry/opentelemetry-dotnet#1632]
# Bug Report

NuGet packages:

* `<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc1.1" />`
* `<PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.0.0-rc1.1" />`

Runtime version: `net5.0`

## Symptom

When adding OtlpExporter to an Asp core web application the pipeline stops working.
Similar to #1616 but I do not see any exceptions being thrown, the application continues working and serving its traffic, but no telemetry seems to be sent to the exporters.

**What is the expected behavior?**

Data being shown in the Console and OTLP exporter

https://github.com/evilpilaf/OpenTelemetryIssue

**Comment by utpilla** [comment]
@evilpilaf I noticed that you're passing the wrong URL to the endpoint in the OtlpExporterOptions:

```
.AddOtlpExporter(config =>
                    {
                        config.Endpoint = $"{this.Configuration.GetValue<string>("OPENTELEMETRYAGENT")}:55680";
                    })
```

 Currently, OTLP exporter only supports gRPC protocol so you'll have to update the endpoint to match that of the OTLP receiver's `gRPC` endpoint which is `http://localhost:4317`. 

`http://localhost:55681` is the OTLP receiver's `http` endpoint.

The URL should either be `http://localhost:4317` or `http://host.docker.internal:4317`.

I would also recommend you to update the core components for OTel to `1.0.1` and non-core components to `1.0.0-rc2`. Once you do that you'll have to pass a `Uri` instead of a `string` as the OtlpExporter Endpoint.

**Comment by evilpilaf** [comment]
Hi @utpilla thanks for the reply, indeed with the latest version of the library I've not experienced any problems whatsoever, so whatever was causing this issue has since been solved.

**Comment by huy7070** [comment]
@utpilla Does the OTLP exporter support HTTP now?

**Comment by utpilla** [comment]
@huy7070 It is supported for Traces and Metrics but not Logs.
