### ISSUE TITLE
Consider adding ApiCompat to CI

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1711]
Currently we're using https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/CONTRIBUTING.md#public-api to detect potential API compatibility break.
.NET team has a new tool which covers more scenarios https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.ApiCompat that we might want to adopt.

**Comment by cijothomas** [comment]
Thanks to @TimHess , #2075 added this capability. Here are the follow ups
1. .NET Team is moving this tool into a separate package, along with other compact check tools. We'll need to adjust accordingly as it happens. - @utpilla 
2. Only enabled for core packages now, as only core packages have ever released stable package. Need to update this once non-core components also release stable. - @cijothomas 
3. The check is part of a non-mandatory CI now, as the tool itself is new and we don't want to break existing CI if the tool has issues. Once the tool is stable, (expected by .NET 6 release time), we can make this CI check mandatory. @cijothomas 
4. The CI check is failing today. @utpilla has investigated this and opened https://github.com/dotnet/arcade/issues/7511, as this is likely a tooling issue. @utpilla 
5. Need to update the release process, so that every stable release updates the "base or contract" version to check compat against. @cijothomas
