### ISSUE TITLE
Review namespace and organization of Baggage APIs

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#1785]
The specification suggests Baggage as a top-level API https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/library-layout.md#api-package.

Currently `Baggage` is in the `OpenTelemetry` namespace https://github.com/open-telemetry/opentelemetry-dotnet/blob/fe2476852131c3bc3a4b5b190cd5970cf46059a9/src/OpenTelemetry.Api/Baggage.cs#L22-L31

and the `BaggagePropagator` is in the `OpenTelemetry.Context.Propagation` namespace https://github.com/open-telemetry/opentelemetry-dotnet/blob/fe2476852131c3bc3a4b5b190cd5970cf46059a9/src/OpenTelemetry.Api/Context/Propagation/BaggagePropagator.cs#L24-L30

The spec seems to suggest something more like:

```csharp
namespace OpenTelemetry.Baggage
 { 
     public readonly struct Baggage : IEquatable<Baggage> 
     {
```

and 

```csharp
namespace OpenTelemetry.Baggage.Propagation
 { 
     public class BaggagePropagator : TextMapPropagator 
     { 
```

OpenTelemetry.Baggage.Baggage kinda feels ewwwww... 🥴 

I'm not familiar enough with baggage to know what kind of thought went into the organization we have. Hoping for other's input. @CodeBlanch @reyang @cijothomas

**Comment by reyang** [comment]
## Short version

I would suggest that we avoid `OpenTelemetry.Baggage.Baggage` as hard as we could.

## Long version

I think for languages like JavaScript/Python, it will be easier since they can have a namespace called `OpenTelemetry.Baggage` and then several functions under that namespace (without having a class). E.g. this is what OTel Python is doing https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/baggage/__init__.py.

OpenTelemetry Java is matching closely with [the spec](https://github.com/open-telemetry/opentelemetry-java/blob/d71db8cbea70c95ac93c129559a948024de71cc9/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java#L10) but the good thing is that one can easily tell from upper-case vs. lower-case `io.opentelemetry.api.baggage.Baggage`.

In C# I don't see a good way to match what Java does, and having a `OpenTelemetry.Baggage.Baggage` is very confusing (we've already hit the [`Console` issue](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1332)).

My understanding is that [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/library-layout.md#opentelemetry-project-package-layout) is giving language owner rights to make it idiomatic by saying "This package layout is intentionally generic and it doesn't try to impose a language specific package structure".

**Comment by alanwest** [comment]
Yes agreed `OpenTelemetry.Baggage.Baggage` is confusing. Is there any reason we wouldn't just put Baggage under `OpenTelemetry.Context.Baggage`?

**Comment by reyang** [comment]
> Yes agreed `OpenTelemetry.Baggage.Baggage` is confusing. Is there any reason we wouldn't just put Baggage under `OpenTelemetry.Context.Baggage`?

I guess the only reason is that the spec put baggage and context as brothers?
* https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/baggage
* https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/context

**Comment by alanwest** [comment]
In that case then we're good with BaggagePropagator being in `OpenTelemetry.Context.Propagation.BaggagePropagator`?

**Comment by reyang** [comment]
I personally would think `OpenTelemetry.Context.Baggage` and `OpenTelemetry.Context.Propagation.BaggagePropagator` make more logical sense 😆

**Comment by alanwest** [comment]
Ha, yea that's what my intuition said too! Though it's also a pretty minor thing... just popped out at me in doing a final review of the API.

@cijothomas what's your gut say about moving Baggage to the `OpenTelemetry.Context` namespace? Would this just complicate things at this point?

**Comment by cijothomas** [comment]
> In that case then we're good with BaggagePropagator being in `OpenTelemetry.Context.Propagation.BaggagePropagator`?

Yes. All propagators in Otel.Context.Propagation, Baggage is no exception.

**Comment by cijothomas** [comment]
> @cijothomas what's your gut say about moving Baggage to the `OpenTelemetry.Context` namespace? Would this just complicate things at this point?

Agree its slightly more correct to have Baggage under Context. But the benefit is small compared to making a last minute change.

**Comment by cijothomas** [comment]
Closing this as we have reached 1.0 and no breaking changes can be made.
