### ISSUE TITLE
Exception stack trace recorded without stack trace 

### ISSUE THREAD

**Issue by valeraf23** [open-telemetry/opentelemetry-dotnet#1912]
I use AspNetCoreInstrumentation(x =>
                {
                    x.RecordException = true;
                });
 with OtlpExporter which export traces to elasticsearch 
 
 When rising exception it recorded without stack trace 

![1fa962bae8584de676a43f57b237e5ca - Errors - nmaster - Services - APM - Elastic - Google Chrome 2021-03-16 16 11 48](https://user-images.githubusercontent.com/6804802/111323484-98083300-8672-11eb-918e-854b5cbe2b6f.png)

**Comment by cijothomas** [comment]
Its not possible to determine if there is an issue with the SDK/Asp.NetCore Instrumentation/OTLP Exporter without a repro.
Please share a minimal repro demonstrating issue.

To ruleout issue with SDK/Asp.NetCore instrumentation - add ConsoleExporter and see if it prints the exception information. If it does print, but the OTLPExporter doesn't then its an issue in OTLP Exporter. Else its an issue in the Asp.Net core instrumentation itself. Either way, please share a repro and re-open the issue .

**Comment by seungyongshim** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c638b56ce5d1b2cc16ad833602b5b6bf6e480d5d/exporter/elasticexporter/internal/translator/elastic/exceptions.go#L76

I'm so sad. Today, Collector has only using exception stacktrace to support language "JAVA" :(

**Comment by a-vivona** [comment]
I have encountered the same problem as @valeraf23.
I also use the OtlpExporter which exports the traces directly to Elasticsearch (APM server), without going through the OTLP Collector.

However the problem is not with the SDK/Asp.NetCore instrumentation nor the OTLP Exporter.

The problem comes from ElasticSearch which receives the stack trace provided by the Asp.NetCore instrumentation, but does not currently know how to process it for display.

See https://github.com/elastic/apm-server/issues/5795

@valeraf23: you can view the stack trace from the "Discover" page in the "JSON" tab.
![image](https://user-images.githubusercontent.com/13315578/151585090-efaa4263-e3ce-4dfd-af60-e37bebe2b8d3.png)
