### ISSUE TITLE
Open Telemetry Logs Samples, Documentation and OTLP Support

### ISSUE THREAD

**Issue by RehanSaeed** [open-telemetry/opentelemetry-dotnet#2076]
I'm interested in learning more about how to setup OT logs and then using an OTLP exporter to push them out. I have read the [documentation](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/getting-started/README.md) and have several questions.

1. Is pushing logs over OTLP supported yet?
2. Is there a sample I can look at?
3. If I can get it all working, how do I know which products support OT logs? What happens if I push them to Jaeger for example which I suspect would not support them?
4. How does this approach compare with pushing [log data into Activity.Events](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1739)?
5. Do we have to configure exporters twice? Once for tracing and once for logs?

**Comment by cijothomas** [comment]
Is pushing logs over OTLP supported yet? - No. There is WIP PR to add that capability, but not yet merged. No ETA on when'll happen, but its likely *after* 1.2.0 (which adds metrics support)

Is there a sample I can look at? https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs

If I can get it all working, how do I know which products support OT logs? What happens if I push them to Jaeger for example which I suspect would not support them? - not sure thats a question for this repo, as the only exporter shipped from this repo is the Console one today. 

How does this approach compare with pushing log data into Activity.Events? -Traces and Logs are standalone, independent pillars. You may use them as such, or you want to send logs embedded inside Activity, if your backend support it. If sending logs as Activity.Event, samplers may affect it. As of today, there is no "sampler" concept in Logs.

Do we have to configure exporters twice? Once for tracing and once for logs? - Yes. https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/AspNetCore has setup both traces and logs (and metrics too soon).
