### ISSUE TITLE
Jaeger exporter to use the official nuget for thrift

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2161]
Instead of the current copy-paste from official thrift, we can migrate to official nuget, now that we removed .NET Core 2.1 and older than .net framework 461 support.

https://github.com/open-telemetry/opentelemetry-dotnet/pull/2119/files#r672558653

**Comment by joaopgrassi** [comment]
I will take a look at this, now that the dependencies should be good without old tfms.

**Comment by joaopgrassi** [comment]
I'm not familiar with thrift, but I just took a quick look and found out that:

- The latest version of `ApacheThrift` has a dependency on `System.Threading.Tasks.Extensions (>= 4.5.4) `, so we either need to bump our version of `System.Threading.Tasks.Extensions` or take `ApacheThrift` version `0.14.2`

- It seems the package only offer async APIs, and we are using sync everywhere. I found this PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/1374 which was when it was reverted due to an issue. I guess taking the NuGet package means we need to go back to async?

**Comment by joaopgrassi** [comment]
I went ahead and use the NuGet package and brought back the changes how they were before #1374. https://github.com/joaopgrassi/opentelemetry-dotnet/commit/05fa354e04f28b1bbb74c4e8fb45ea0e1bd68de3

Some new methods/properties came from `TTransport` (`public override TConfiguration Configuration`) and these methods: https://github.com/joaopgrassi/opentelemetry-dotnet/blob/05fa354e04f28b1bbb74c4e8fb45ea0e1bd68de3/src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerThriftClientTransport.cs#L84

I'm not familiar with this, so I guess I'll need some guidance/help. The tests are passing, but I'm on Linux. Will try later to run on a Windows vm.

**Comment by cijothomas** [comment]
Given jaeger exporter is not going to get any new features, we can close this issue.
