### ISSUE TITLE
Add wildcard support to AddLegacySource 

### ISSUE THREAD

**Issue by pakrym** [open-telemetry/opentelemetry-dotnet#2183]
Azure SDKs produce activities that have tags and links set and don't need extra enrichment. 

For client level spans we use the client and method name as activity name (i.e. `BlobClient.Download`) so it's impractical to use the existing `AddLegacySource(string name)` to collect them as customers would need to add every individual method they use.

Feature request:

Add wildcard support to AddLegacySource the same way it exists in AddSource so customers can write

```
.AddLegacySource("Azure.*");

**Comment by pakrym** [comment]
cc @cijothomas

**Comment by lmolkova** [comment]
I tried to list all possible legacy sources. The problem is that Azure SDK sources are per operation and don't have any pattern in the name:

For EventHub it's bearable:

```csharp
  .AddLegacySource("EventHubs.Message")
  .AddLegacySource("EventHubProducerClient.Send")
  .AddLegacySource("EventProcessor.Process")
  .AddLegacySource("EventProcessor.Checkpoint")
```
  
But Storage does [this](https://github.com/Azure/azure-sdk-for-net/blob/49ee0b4577c88bc70c235613f37fdf2f704f3a3f/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L946): `$"{nameof(BlobBaseClient)}.{nameof(Download)}"`

So wildcards won't really help and we'll have to find another way.
