### ISSUE TITLE
OpenTelemetry Exporter causes significant performance lag when collector isn't running

### ISSUE THREAD

**Issue by smarsh-gregj** [open-telemetry/opentelemetry-dotnet#2402]
# Bug Report

NUGET PACKAGES
OpenTelemetry v1.1.0
OpenTelemetry.Exporter.OpenTelemetryProtocol v1.1.0
OpenTelemetry.Extensions.Hosting v1.0.0-rc7
OpenTelemetry.Instrumentation.AspNetCore v1.0.0-rc7

RUNTIME 
net5.0

## Symptom

When using the OpenTelemetry Exporter, if the collector that is configured to be sent to is not running, a significant performance hit is experienced.   (Approximately 4 seconds per request when pointing to localhost...Even longer for a remote host that isn't listening)

**What is the expected behavior?**

Diagnostic/Tracing code should have as little effect on application performance as possible

**What is the actual behavior?**

When the collector isn't running at the specified location there is a big performance hit

## Reproduce

I have attached a zip file of the default ASP.Net WebApi project with only OT instrumentation added.  OT Endpoint is configured in appsettings.json.   Right now it is pointing to localhost:4317.  If there is no collector running it should take 4+ seconds to return data.  If you point it to a valid collector though it will return almost immediately.

[WebAppForLoadTesting.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/7211838/WebAppForLoadTesting.zip)

**Comment by cijothomas** [comment]
It looks like you are using Simple export processor, and for that, every activity is exporter without any batching, and from the same thread activity is being stopped (i.e same thread responding to the webrequest). This is the expected behavior.

Switch to the BatchExportProcessor (that what you'll get by default), and export occurs in a diff. thread than the one serving the web request.

**Comment by smarsh-gregj** [comment]
Thanks!  Switching to Batch solved the problem.
