### ISSUE TITLE
OTLP HttpExporter does not allow overriding path

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2483]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp-request We seem to be appending /v1/traces by default, including if user provided custom endpoints.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L106

Should we be doing this only if the default endpoint is used, so that users provided endpoint is not appended with the /v1/traces path.?

**Comment by cijothomas** [comment]
@rypdal @alanwest -Could you help with the qn?

**Comment by rypdal** [comment]
According to the latest (specification)[https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp] an endpoint created from the OTEL_EXPORTER_OTLP_ENDPOINT env.var. is appended either with v1/traces or v1/metrics in case of http/protobuf. Same rule is applied to Endpoint property set explicitly from code. If user wants to have custom traces, metrics endpoint he has to use signal specific env. vars. OTEL_EXPORTER_OTLP_{Signal}_ENDPOINT. Another thing is that we are not supporting any specific env. vars. yet. For this we need dedicated issue, because signal specific env. vars. has to be supported for the case of gRPC as well. Moreover, we need to support signal specific env. vars, for many env. vars. like Headers, Timeout, Protocol, etc (full table of env. vars.)[https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#opentelemetry-protocol-exporter]. I think we need issue like "Support signal specific environment variables".

**Comment by joaopgrassi** [comment]
Hey all,
Should we close this issue? I think the original problem is solved, even though we still need to address the signal-specific env vars.
