### ISSUE TITLE
Provide guidance on how to operate

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2587]
Are there plans to provide guidance on how to operate the integration?

For example, how do you gain insights if the metrics reader is not able to talk to the OTLP collector that is configured?

**Comment by cijothomas** [comment]
Are you referring to https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#troubleshooting

There is related issue for ensuring the right logs are produced : https://github.com/open-telemetry/opentelemetry-dotnet/issues/2543

We are considering adding stats about # of items lost due to cap etc. similar to https://github.com/open-telemetry/opentelemetry-dotnet/pull/2331

**Comment by tomkerkhove** [comment]
Oh it's part of the src/ folder - Are you open for PRs to add this to the README?

Any plans to plug in to .NET's ILogger so that we can use a streamlined approach?
