### ISSUE TITLE
Provide capability to have more advanced ASP.NET Core telemetry for metrics

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2589]
# Feature Request

**Is your feature request related to a problem?**

Provide capability to have more advanced ASP.NET Core telemetry allowing us to add more information such as routes which are not supported today.

**Describe the solution you'd like:**

Configure this through the options of the extension

**Describe alternatives you've considered.**

We are currently working around this by writing our own middleware to provide more information

## Additional Context

N/A

**Comment by cijothomas** [comment]
We have Enrich in ASP.NET Core today.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore#enrich

If there are scenarios not covered by this, please describe them for tracking.

**Comment by tomkerkhove** [comment]
Sorry, my feature request was not thorough enough as I'm asking for the metrics aspect of it.

In the extension there are still a few to-dos that need to be tackled.

**Comment by cijothomas** [comment]
Yes the instrumentation for metrics are very early stage. It'll be prioritized after the core SDK is done. We are happy to get contributions, if you are interested in!

**Comment by tomkerkhove** [comment]
I will try to have a look when I have time, but no promises

**Comment by ktmitton** [comment]
@tomkerkhove I think I'm ready to take a stab at a _real_ contribution, what kind of metrics are you looking for?

**Comment by tomkerkhove** [comment]
Sure, from top of mind:

- # of requests (tags: status code)
- # of failed requests
- # of successful requests
- Request duration (already there I think)

**Comment by ktmitton** [comment]
Not sure if I'm being too conservative here, but if we are tagging number of requests with status codes, so we need separate metrics for failed/successful, or can that be handled downstream by filtering data?

**Comment by tomkerkhove** [comment]
No problem at all. From my side I'd say it can be beneficial because not all systems support this; for example Prometheus allows you to sum those up but not all of them.

But I'm not a metrics expert.

**Comment by tomkerkhove** [comment]
What I would do though, is make sure people can opt-out and/or extend the metrics that are being emitted fairly easily

**Comment by ktmitton** [comment]
There's still something I'm trying to figure out, but...it looks like this might be something low-cost where you filtering isn't strictly necessary. I've looked at the prometheus implementation in the past, and that relied on middleware, which I think made sense to make sure you have filters so you can limit overhead.

So...uh...it looks like we've been set up pretty well, here. I've got an oddity to work out, but looks like we can easily piggyback off the request duration metrics:
![image](https://user-images.githubusercontent.com/2873724/143409277-c615b252-6623-4e0b-8fd0-14deb6b15dcb.png)

Once I work out something, I'll get a branch actually pushed for people to reference.

**Comment by ktmitton** [comment]
Throwing this out there in case my understanding is wrong...

The oddity I'm seeing is the counter resets between every reporting. I'm used to Prometheus metrics, where the counter just keeps growing, but now I'm wondering if the reporting only reports the diff, and it's up to the collector to keep the running total. That would kind of make sense, since it would allow the count to persist across server restarts...

**Comment by ktmitton** [comment]
I need to pay more attention to the issues I'm following, just commented on a completely unrelated one twice...

Ok, so I figured out my oddity, I didn't know about AggregationTemporality, now what I'm seeing makes sense.

I'll try to clean up my code later, see what testing looks like, then get a PR together for basic request count metrics. I think I want to do a separate PR to add the success/failure metrics, though, because I think that needs more of a conversation with people who have been in this for a while. I have some reservations about breaking it down like that. It seems like at that point we're catering to specific consumers, and it seems like a thing that can blow up.

What if success/failure isn't enough, and people want to split it into success/client failure/server failure?
Where does that stop?

I'm not saying success/failure won't be justified, just that it's murky enough I would like to separate that from the basic request count, so we don't have to hold up the one we know we should do for the ones we have questions on.

**Comment by ktmitton** [comment]
@cijothomas would I be correct in assuming there's overlap between this issue and #2556?

**Comment by cijothomas** [comment]
> @cijothomas would I be correct in assuming there's overlap between this issue and #2556?

Both would have totally different implementation, but they are expected to produce similar metrics. (following OTel semantic conventions for Metrics from a Http based Server)
