### ISSUE TITLE
rabbitmq default user and pass needs to be updated in the MicroserviceExample's docker-compose 

### ISSUE THREAD

**Issue by mehrdad-goudarzi** [open-telemetry/opentelemetry-dotnet#2655]
I tried to run the sample to check the output but something needed to be fixed in the docker-compose, rabbitmq section.

this is the container's log for rabbtmq:

```
error: RABBITMQ_DEFAULT_PASS is set but deprecated

error: RABBITMQ_DEFAULT_USER is set but deprecated

error: deprecated environment variables detected


Please use a configuration file instead; visit https://www.rabbitmq.com/configure.html to learn more
```

**Comment by ktmitton** [comment]
This was an interesting one, I wasn't able to replicate your issue for a while...

@mehrdad-goudarzi can you try running `docker pull rabbitmq:3-management-alpine`?

Looks like with 3.9.0, they introduced this issue, but they reversed it back in August starting with 3.9.4:
https://github.com/docker-library/docs/pull/2012

My suspicion is you pulled 3-management-alpine between 3.9.0 and 3.9.3, so that's what you had cached locally, the docker pull command above should work, assuming you are pulling your images from dockerhub.

Looks like this will eventually be an issue later, and I'll look into resolving it now, but hopefully this will get you moving!

**Comment by ktmitton** [comment]
Yeah, so this was an interesting read, for now it looks like these variables will be around for a while:
https://github.com/docker-library/rabbitmq/issues/508

That being said, since we're using guest/guest, we don't technically need to manually set them in the environment variables of the rabbitmq image, and we could just create a pull request to try and remove them. Before I do that, though, I'm having trouble actually building the dotnet images I'd like to solve. I'm getting an issue with the language version being set to 10, my guess is because the build images are running netcore 3.1.

Are you able to pull a fresh master and run `docker-compose build --no-cache`?
