### ISSUE TITLE
NuGet Install Fails, Cycle Dectected

### ISSUE THREAD

**Issue by lkruger** [open-telemetry/opentelemetry-dotnet#2681]
# Bug Report

OpenTelemetry.Exporter.Console v1.1
OpenTelemetry.Exporter.Console v1.2.0-beta2.1

## Symptom

Install the OpenTelemetry Nuget Package fails with a "Cycle detected." error.

## Reproduce

1.  Create a new .Net6.0 Project in VS2022
2. Attempt to install the OpenTelemetry.Exporter.Console package.

**Comment by lkruger** [comment]
The install appears to work with a Console application, but fails with the "Cycle Detected" error when using an ASP.NET Core Web App (Model-View-Controller) project.

**Comment by ktmitton** [comment]
Interesting, tried to replicate this via command line but couldn't, so it seems like it may be specific to VS2022, not dotnet. Here's what I've tried so far that didn't exhibit the issue:

```shell
dotnet new webapi -o test
cd ./test
dotnet add package OpenTelemetry.Exporter.Console --prerelease
```
```shell
dotnet new mvc -o test
cd ./test
dotnet add package OpenTelemetry.Exporter.Console --prerelease
```

If I get time, I'll try to install vs and dig into this more, just dropping that information in case it helps somebody else.

**Comment by ktmitton** [comment]
@lkruger trying to figure out how to replicate your issue and I'm still missing something. Does this look like what you were doing:
![image](https://user-images.githubusercontent.com/2873724/143375752-fe0d0481-5031-4de9-87c8-7ce4cee9f037.png)

**Comment by autiarii** [comment]
I have same problem with vs2022 while trying to install via vs interface. Works fine with Rider or command line

**Comment by ktmitton** [comment]
@autiarii I'm am _not_ very fluent in vs, I use it very rarely. Can you help me understand this by being _very_ explicit on the steps you're following so I make sure I do the same thing? Screenshots would be much appreciated!

**Comment by ktmitton** [comment]
I'm pretty confident that's the case base on this test:
![image](https://user-images.githubusercontent.com/2873724/143414575-e6680b5a-4a66-43a9-920b-9477fd56c6c9.png)
![image](https://user-images.githubusercontent.com/2873724/143414648-a14f9c5b-5100-4aed-8fef-980bfdf55f52.png)

I'll take a look at this later today, want to find some documentation backing this up, but I think I'll be able to get s simple request count out later today!

**Comment by ktmitton** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/2873724/143415570-4baef1aa-8bf9-429b-bc64-7a10d51a63c5.png)

Ok, so I'll try to clean up my code later, see what testing looks like, then get a PR together for basic request count metrics. I think I want to do a separate PR to add the success/failure metrics, though, because I think that needs more of a conversation with people who have been in this for a while. I have some reservations about breaking it down like that. It seems like at that point we're catering to specific consumers, and it seems like a thing that can blow up.

What if success/failure isn't enough, and people want to split it into success/client failure/server failure?
Where does that stop?

I'm not saying success/failure won't be justified, just that it's murky enough I would like to separate that from the basic request count, so we don't have to hold up the one we _know_ we should do for the ones we have questions on.

**Comment by autiarii** [comment]
@ktmitton I have tried to repeat it again, but had no success. My initial steps were

- launch visual studio 22, create new c# project (.net 6)
- manage nuget packages, install latest OpenTelemetry.Exporter.Console
- accept dependencies installation
- issue appears at this step

**Comment by lkruger** [comment]
Looks like it was a VS issue.  When I upgraded to the latest VS, the issue went away.

**Comment by GrayWinst** [comment]
I noticed a difference in behavior using Visual Studio with PackageReference (where I was not able to install the package) and Packages.Config (where I was able to install the package).
