### ISSUE TITLE
Is there any plans for Unity / Mono support?

### ISSUE THREAD

**Issue by JackRhodes** [open-telemetry/opentelemetry-dotnet#2713]
# Question

Does the Open Telemetry SDK currently have any plans to support Unity / mono?

**Describe your environment.**

We have game clients and game servers using Unity. These then communicate with a gateway, which then communicates to numerous .NET Core microservices. We use tracing so we can see where each request goes and how long it takes.

**What are you trying to achieve?**

We use jaeger in our .NET services alongside open telemtery, so can see traces from the gateway, but do not have full visibility from the end client.

I am looking to see if it is possible to use the OpenTelemetry SDK on a mono based game server, so I can then get a full end to end trace from a game server => backend service, instead of gateway => service. I would use the console exporter and a jaeger collector. I would like to know if there is any plans to support this, or if there are only plans to support .NET framework / Core

**Comment by cijothomas** [comment]
The API/SDK/Exporters do have netstandard2.0 target already, so they should be able to be used on all platforms implementing netstandard2.0.
(I dont recollect anyone asking for this before, so this was not discussed ever. But based on ^ comment, it may already be working)

**Comment by AfonsoBatista7** [comment]
Have anyone been able to run OpenTelemetry in Unity? 

I tried creating a new simple Unity project, just to test sending a log message to an otel-collector running on a docker container but the log is never received by the collector. In another hand I tested a simple .NET project that only sends one log to the collector and it works fine... So my conclusion was that, this could be an issue with Unity... 

Does anyone know if OpenTelementry is incompatible with Unity or how to resolve this issue?

**Comment by russelljahn** [comment]
> Have anyone been able to run OpenTelemetry in Unity?
> 
> I tried creating a new simple Unity project, just to test sending a log message to an otel-collector running on a docker container but the log is never received by the collector. I also tested a simple .NET project that only sends one log to the collector and it works fine... So my conclusion was that, this could be an issue with Unity...
> 
> Does anyone know if OpenTelementry is incompatible with Unity or how to resolve this issue?

I looked into this a bit and can confirm the OpenTelemetry SDK is incompatible with Unity's forked Mono version.

Specifically, the SDK relies on the built-in .NET [EventListener class](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener?view=netstandard-2.0) from `System.Diagnostics.Tracing` to wire up written metrics. Unity's Mono has [stubs](https://github.com/Unity-Technologies/mono/blob/unity-main/mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs) for `EventSource` and `EventListener` to compile, and there isn't an underlying diagnostic dispatcher class to fire the events. So the SDK silently fails because these built-in .NET features aren't implemented on Unity's side.

To make this work in Unity's Mono, you'd need to rewrite the SDK to use a different mechanism to wire up events. My guess is this isn't going to happen.

However, in theory, when Unity migrates from a forked Mono to CoreCLR in 6.7/6.8, these diagnostics classes would be supported. Then the OpenTelemetry SDK would work as-is.
