### ISSUE TITLE
Prometheus support for middleware injection

### ISSUE THREAD

**Issue by twenzel** [open-telemetry/opentelemetry-dotnet#2776]
Using the Prometheus exporter results in an endpoint which can't be protected by any authentication.

Use case:
We're using the Prometheus exporter to provide metrics for the Prometheus service. Unfortunately the endpoint is reachable for everyone because it does not support a build-in authentication (which I'm totaly fine with).

To protect the endpoint, e.g. with a simple basic authentication, it should be possible to inject a custom middleware.
There are three possible options.

**Option 1**
Provide option to use `PrometheusExporterMiddleware` directly.
```csharp
app.Map("/metrics", metricsApp =>
{
    metricsApp.UseMiddleware<BasicAuthMiddleware>("Contoso Corporation");
    metricsApp.UseOpenTelemetryPrometheusMiddleware();
});
```` 

**Option 2**
Provide injection point:
```csharp
 public static IApplicationBuilder UseOpenTelemetryPrometheusScrapingEndpoint(this IApplicationBuilder app, MeterProvider meterProvider = null, Action<IApplicationBuilder> injectionPoint = null)
{
    var options = app.ApplicationServices.GetOptions<PrometheusExporterOptions>();

    string path = options.ScrapeEndpointPath ?? PrometheusExporterOptions.DefaultScrapeEndpointPath;
    if (!path.StartsWith("/"))
    {
        path = $"/{path}";
    }

    return app.Map(
        new PathString(path),
        builder => {
    injectionPoint ?.Invoke(builder); // <-- inject custom middleware here
    builder.UseMiddleware<PrometheusExporterMiddleware>(meterProvider ?? app.ApplicationServices.GetRequiredService<MeterProvider>()); 
    });
}
```

**Option 3**
Provide build-in (Basic) authentication support, so we don't need to inject a custom middleware.

I'm totaly fine with any option and would provide a PR.

**Comment by tillig** [comment]
It looks like some of this was addressed in #2414, however, in our system we have metrics and health checks served on a different port than the rest of the API. It's not a separate _server process_, it's `IApplicationBuilder.MapWhen` along with a delegate that also checks the port.

The [current implementation of `UseOpenTelemetryPrometheusScrapingEndpoint`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/778052f67f58b945be7c046bb57a8f3dc3be57c1/src/OpenTelemetry.Exporter.Prometheus/PrometheusExporterApplicationBuilderExtensions.cs#L43) doesn't account for port - it seems like the current mechanism is _either_ "dedicated listener port + path for metrics" (where health checks couldn't be on that same port) _or_ "path is on the main port always."

I can't write my way around it because `PrometheusExporterMiddleware` is internal.

I think there's value in providing more direct access to the `PrometheusExporterMiddleware` to enable these sorts of use cases without having to complicate the `PrometheusExporterOptions`.
