### ISSUE TITLE
Start Root Span Collects Current Active Span as Parent

### ISSUE THREAD

**Issue by omamoo** [open-telemetry/opentelemetry-dotnet#2803]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):

* NuGet: OpenTelemetry.Api Version 1.2.0-rc1

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

* dotnet 6.0.101

## Symptom

I defined simple Api endpoint with the following code:
```
[HttpGet]
public async Task TestOtel()
{
    using (TracerProvider.Default.
               GetTracer(ActivitySourceProvider.ActivitySourceName, ActivitySourceProvider.Version).
               StartActiveSpan("FirstSpan"))
    {
        await Task.Delay(5.Seconds());
        var rootSpan = 
            TracerProvider.Default.
                GetTracer(ActivitySourceProvider.ActivitySourceName, ActivitySourceProvider.Version).
                StartRootSpan("MyRootSpan"); 
        using (Tracer.WithSpan(rootSpan))
        {
            Task.Delay(5.Seconds());
        }
    }
}
```

**What is the expected behavior?**

I'm expecting to see two different traces:
* First one is for incoming HTTP request (using AspDotNet instrumentation library) and one more nested span called "FirstSpan"
* Second is for the MyRootSpan which created by using `CreateRootSpan` and activated with `WithSpan` method.

**What is the actual behavior?**

One trace with all span see attached image.

## Additional Context
Image with trace at Jaeger:
![image](https://user-images.githubusercontent.com/91830944/150417633-2c309132-d438-4a31-bba3-9796b238f618.png)

Thanks for the help.

**Comment by omamoo** [comment]
Anyone?

**Comment by alanwest** [comment]
Yes, this might be a bug. I created a test #2878 that I think models your situation.

**Comment by omamoo** [comment]
@alanwest Yes this is the exact case, thanks. How can I know if the test passes?

**Comment by alanwest** [comment]
We'll leave this issue open as I'm not yet sure what the best fix will be.

In my opinion, the problem is due in part to the behavior of the `StartActivity` activity method when it is passed an empty parent context (i.e., starting a root span). `StartActivity` is called from `StartRootSpan` and is not part of the OpenTelemetry .NET project - it is part of .NET's System.Diagnostics library.

I'll raise this issue for discussion in the .NET SIG meeting agenda next week.

In the meantime, a work around for you may be to set `Activity.Current =  null` prior to calling `StartRootSpan`. It is the fact that `Activity.Current` is not null which is causing `MyRootSpan` to be a child of `FirstSpan` in your case.

**Comment by omamoo** [comment]
@alanwest Thanks for the update.

- We are using the workaround as you described, so it's don't urgent. 
- I raised this issue because I couldn't find #984, they are the same.
- Yes, the problem is with .NET diagnostics library and activity which is not null. But you won't change the API of span creation am I right? If I'll call `CreateActiveSpan` with null span context it still will use the parent span if exist as a parent? 

Thanks.

**Comment by Oberon00** [comment]
I don't think this is the same as #984. While #984 is about the Activity API missing required basic functionality, this is about the OTel-specific StartRootSpan not doing what it says in its name.
