### ISSUE TITLE
Support for OTLP exporter signal-specific environment variables

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry-dotnet#2923]
# Question

I searched for an existing issue around this topic but couldn't find one. So I thought of opening this as a question so we can start a discussion and maybe kick off some work for it. 

**What are you trying to achieve?**

I remember this issue https://github.com/open-telemetry/opentelemetry-dotnet/issues/2483 where we improved things and also where we had some discussions about the signal specific env vars (OTEL_EXPORTER_OTLP_{Signal}_ENDPOINT). But the implementation of the signal-specific env vars was to be done in a follow-up, which made sense.

Looking at the [spec compliance matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables) the line on `OTEL_EXPORTER_OTLP_*` "checks" for .NET, which is not entirely true since we don't seem to support the signal-specific env vars. That is a spec issue, but I believe this can confuse users nonetheless. 

**What did you expect to see?**

That the SDK supports the signal-specific env vars as it's marked on the compliance matrix.

**Comment by luizhlelis** [comment]
Hello @joaopgrassi,
I'm [trying to figure out](https://github.com/luizhlelis/opentelemetry-dotnet/commit/d220758de57e027659f9777f6d5e5b0c3038473e) how to solve this issue by adding support to signal-specific env vars. But I realize it won't be that simple because, currently, `OtlpExporterOptions` has only one [Endpoint](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L113). Do you have any suggestions?

**Comment by luizhlelis** [comment]
@pellared, wouldn't it be better to close this issue as there is another ongoing one?

> **NOTE:** the current one is opened to community contributions

**Comment by joaopgrassi** [comment]
Feel free to close this in favor of #4154.
