### ISSUE TITLE
Make CI checks faster

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#3014]
![image](https://user-images.githubusercontent.com/5232798/157733465-e366e7a9-83cb-4b76-b28f-71a3479a52f8.png)

It looks like a good amount of time is spent on nuget restore. And majority of them from the example projects, which are not required for all the build/test pipelines. We may benefit, if examples are built in a dedicated pipeline, and ignored by other pipelines.

**Comment by cijothomas** [comment]
@mic-max will try to check this.

**Comment by cijothomas** [comment]
@mic-max Can you comment if this still has open items?

**Comment by ngruson** [comment]
Ok if I look at this?

**Comment by cijothomas** [comment]
> Ok if I look at this?

sure! Thanks for helping.

**Comment by ngruson** [comment]
@cijothomas As is, I don't see NuGet restores taking 5 minutes like in your screenshot. It's more like 2 minutes now on Windows agents.

In my fork, I moved the example projects to a separate solution so that these projects are not built during CI.
Another GitHub Actions workflow is building the examples solution separately.
But this doesn't make the NuGet restore steps much faster.
Probably because there are still web projects in the main solution like `TestApp.AspNetCore'.
`OpenTelemetry.Instrumentation.AspNetCore.Tests` is depending on `TestApp.AspNetCore' however.

I don't see a need to change the CI workflows imho.
If you still think it's beneficial, I can still create a PR.

**Comment by cijothomas** [comment]
Its hard to give a simple answer for this issue as it is a long while since I actively explored this and the other person who continued this is no longer working on this as well..

If the nuget restore's speed is not going to improve significantly by excluding (and building in a separate CI) docs/examples, then this may not be worth exploring.
