### ISSUE TITLE
[Feature] Subscribe to ActivitySource after build

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet#3253]
# Feature Request

`TraceProviderSdk` should be able to subscribe to activities also after build is triggered in `TraceProviderBuilder`.

Currently we have an issue in [opentelemetry-dotnet-instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) that we are not able to subscribe to the activities when library load is detected after `TraceProviderBuilder` has built `TraceProvider`. One of such libraries are ASP.NET ones. Users have to manually define, if the application is ASP.NET based - which in turn requires to define all enabled libraries manually. We would like to detect automatically all parts that needed to be instrumented and by default include whole set.

(ASP.NET issue lies in direct dependency to ASP.NET framework, where's console app does not contain these libraries. So it will crash in load, if it tries to include ASP.NET instrumentation).

**Describe the solution you'd like:**

Public API to rewrite source listener in `TraceProviderSdk`. 

(Seems like easily doable, the question is if I'm missing something important?)

**Comment by RassK** [comment]
@reyang The original issue comes from here: we are bootstrapping SDK in the startuphook context. By default we would like to add maximum instrumentations set, but doing so with console app will crash the application, due no ASP.NET binaries that the ASP.NET instrumentation requires. In the startuphook context, we have no ways to determine, if the application is console or ASP.NET.

To further optimize the instrumentation set, we are planning to add instrumentations on the fly. Eg when assembly load is detected but the event might come up after the OTel SDK has already built the trace provider. I guess disposing and recreating the whole SDK is not a good alternative.

**Comment by reyang** [comment]
Thanks for the elaboration!

I don't see a fundamental blocker, so I guess it is doable.

I think these are the things we need to explore:
1. if we allow "hot swap", what's the expected behavior (e.g. do we only allow new sources to be added, or we also allow sources to be removed, what would happen during the swap - any potential side effect such as perf/contention/data/propagation)?
2. is this something only needed by auto-instrumentation, or we also expect other developers (e.g. those who use manual instrumentation) to use it (and if yes, what's the most common scenario)?
3. is there a way that we can prototype this in auto-instrumentation and see how it is working?

The current design allows the SDK to fail fast - e.g. if the configuration (e.g. AddSource, AddMeter, AddView) doesn't make sense, the SDK would refuse to initialize by throwing exceptions. Another benefit is that that SDK can do optimizations based on the understanding of the configuration during initialization time. Neither of these are fundamental showstopper, so if we have a good reason to change the behavior (in a non-breaking way of course), I guess we can.

**Comment by RassK** [comment]
Little update:

1. I guess we can leave unload for now until someone specifically requests it. Although I know that it's now possible to unload dlls in a custom load context. 
2. I expect currently only auto instrumentation cases. Slight chance that there will be library that can instrument many sources but opts in only when it sees some specific library loads.
3. I have now a private PoC that works, will try to find a way how to make both sides public. 

Issues I'm currently encountering:
* Most of the necessary logic is inside `TracerProviderSdk` which is internal. `TracerProvider` has the public api but cannot be made to abstract due `public static TracerProvider Default { get; } = new TracerProvider();`. Current workaround is to use public virtual members, but it's more like a hack.
* `ActivityListener` doesn't react to `ActivityListener.ShouldListenTo` changes, although it's not readonly. Possible uncovered edge case? Current fix was to call internal `ActivitySource.DetachListener` and then again `ActivitySource.AddActivityListener`. I'm not sure how safe is it to call this internal api?
* Dynamically opting in to the library instrumentation such as ASP.NET Core requires changes in sources, legacy sources and instrumentations (basically all options). Due legacysources can affect sources filter logic, then legacysources must be added first. Enforcing it could be difficult, but in case of the bug it should be clearly visible, but requires debugging external code (Opentelemetry.dll) to fix it.

**Comment by RassK** [comment]
@reyang 

Here's the rough PoC:
Changes necessary for opentelemetry-dotnet: https://github.com/RassK/opentelemetry-dotnet/pull/1
How we are using it: https://github.com/RassK/opentelemetry-dotnet-instrumentation/pull/237

**Comment by RassK** [comment]
Closing as seems we managed to successfully transform all code to the auto-instrumentation side.
