### ISSUE TITLE
Examples in Readme and disposing of TracerFactory

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#332]
Do we really need to dispose TracerFactory in examples we are giving in readme? Looks misleading

See this comment: https://github.com/open-telemetry/opentelemetry.io/pull/72#discussion_r343770484

**Comment by lmolkova** [comment]
`TracerFactory` lives as long as application lives. When it's disposed it shuts down processors and collectors. It should be disposed to shutdown gracefully.

We should also add `async Shutdown(CancellationToken)`  to the factory, so it could be shut down with timeout (vs dispose).

**Comment by SergeyKanzhelev** [comment]
my point here is that examples may be misleading as it will be extremely rare to write a code like we provide in readme where creating of trace factory is done in `using` statement.

**Comment by thangchung** [comment]
Hi. I think the `TracerFactory` lifetime is a little bit confusing, especially in ASP.NET Core integration with Hosting. Currently, I try to create an example using `OpenTelemetry.Hosting`, `OpenTelemetry.Collector.AspNetCore` and `OpenTelemetry.Exporter.Jaeger`. Any request also traced only once time because `TracerFactory` only works on the `controllers` by wrapping it with `using`, but then in another request, it could not be traced (might it disposed of already). 

Could you please help to make a demo with `ASP.NET Core` using with `TracerFactory` managed? At the moment, only examples for the Console Host template and it really hard for someone like me to approach with `ASP.NET Core` hosting template. I used the OpenTelemetry version is `0.2.0-alpha.110`.

**Comment by ocdi** [comment]
I'm experimenting with OpenTelemetry. I can see basic AspNetCore requests appear on Zipkin with a minimal config. The documentation is really confusing on how we are supposed to augment a span that is currently appearing, with additional spans from within an MVC Controller action, or even in service code. 

Are we supposed to DI `TracerFactory` into a Controller? It doesn't seem right to me but I can't find a good example.

**Comment by MikeGoldsmith** [comment]
Hi @ocdi - the current strategy is for the application to manage the lifetype of the TracerFactory, eg with DI. However, the OpenTelemeltry spec has been expanded to require TracerProvider which will hold a global reference that can be used.

We have #573 & #576 to track adding these to this project.

**Comment by cijothomas** [comment]
Closing as new docs are created. We still need to update opentelemetry.io docs. It'll be handled in the future.
