### ISSUE TITLE
Add http.url to the HTTP metrics instrumentation

### ISSUE THREAD

**Issue by xavirec** [open-telemetry/opentelemetry-dotnet#3387]
# Feature Request

Besides metrics specs being marked as Experimental, I think that it is useful to include [`http.url`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#attribute-alternatives). 

I'm fine to send a PR if you want. It should be a very simple change.

**Comment by kerams** [comment]
Will it create a histogram for every unique URL?

I'd expect to be able to
- exclude URLs unless a non-error status code was returned (to prevent a potential cardinality explosion)
- group URLs together based on subpaths (to prevent a potential cardinality explosion, and also to aggregate metrics over URLs that are logically the same "endpoint")
   - For instance, given an endpoint for file downloads `/download/{fileId}`, I don't want a histogram for every file downloaded. Instead, all requests should be counted towards the `/download/` value of tag `http.url` (or a different one, since `/download/` is not really a URL at that point).

I'm looking into migrating from Prometheus-net, where the request middleware looks like [this](https://github.com/prometheus-net/prometheus-net#aspnet-core-http-request-metrics).

Perhaps there should be some way to inject (or change, should the instrumentation library have the capability to derive this on its own) grouping tags on a per request basis?

**Comment by jnazaren** [comment]
I'm wondering if there were any updates here? I'm also wondering if there's a way to inject http.url or at the very least the name of the asp net core controller action into the default provided asp net core metrics. I know that traces, you can do something like `Activity.SetTag("Key", "Value")` to add an extra column based on an http request object, but I'm wondering if something similar would be possible for metrics?

**Comment by vishweshbankwar** [comment]
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration
