### ISSUE TITLE
.AddOpenTelemetry(c => c.SetTextFormat()) -> Extract() gets not executed (.NET Core 3)

### ISSUE THREAD

**Issue by mwinkler** [open-telemetry/opentelemetry-dotnet#346]
Hi

I implement a `ITextFormat` for Jeager:

```csharp
public class JaegerFormat : ITextFormat
{
    internal static readonly string JeagerHeaderName = "Uber-Trace-Id";

    private static readonly HashSet<string> AllFields = new HashSet<string>() { JeagerHeaderName };

    public ISet<string> Fields => AllFields;

    public SpanContext Extract<T>(T carrier, Func<T, string, IEnumerable<string>> getter)
    {
        // example: 5e9866b886052faf:23f04737ce3da38e:5e9866b886052faf:1
        //              {trace-id}  :   {span-id}    :{parent-span-id}:{flags}
        var traceIdStr = getter(carrier, JeagerHeaderName)?.FirstOrDefault();
        
        Console.WriteLine($"Jaeger header ({JeagerHeaderName}) value: {traceIdStr}");

        if (traceIdStr != null)
        {
            var parts = traceIdStr.Split(':');
            var traceId = ActivityTraceId.CreateFromString((new string('0', 32 - parts[0].Length) + parts[0]).AsSpan());
            var spanId = ActivitySpanId.CreateFromString((new string('0', 16 - parts[1].Length) + parts[1]).AsSpan());
            
            return new SpanContext(traceId, spanId, ActivityTraceFlags.Recorded);
        }

        return SpanContext.Blank;
    }

    public void Inject<T>(SpanContext spanContext, T carrier, Action<T, string, string> setter)
    { }
}
```

and register it at `startup.cs`
```csharp
services.AddOpenTelemetry(builder => builder
    .SetSampler(Samplers.AlwaysSample)
    .AddRequestCollector()
    .AddProcessorPipeline(c =>c.SetExporter(new JaegerTraceExporter(new JaegerExporterOptions{ ... })))
    .SetTextFormat(new JaegerFormat())
);
```

The problem is, that the `Extract()` method of `JaegerFormat` never gets called.

I try to analyze why and found this code in `OnStartActivity()` at `OpenTelemetry.Collector.AspNetCore.Implementation.HttpListener`

```csharp
if (this.hostingSupportsW3C)
{
    this.Tracer.StartActiveSpanFromActivity(path, Activity.Current, SpanKind.Server, out span);
}
else
{
    var ctx = this.Tracer.TextFormat.Extract<HttpRequest>(
        request,
        (r, name) => r.Headers[name]);

    this.Tracer.StartActiveSpan(path, ctx, SpanKind.Server, out span);
}
```
It seems that the `this.hostingSupportsW3C` flag is set to `true` if you use .NET Core 3 (what i using).
Currently i see no way to set this flag to `false` so that the `this.Tracer.TextFormat.Extract()` gets called.
Do I miss something?

**Comment by lmolkova** [comment]
ASP.NET Core 3.0 supports W3C Trace-Context on its own. If tracing is enabled, it always reads Trace-Context headers and starts `Activity` (it's a .NET `Span`).

It could only be turned off only with the ability to trace http calls which is the explicit choice of ASP.NET Core team - they do not provide support for arbitrary protocols.

Since OpenTelemtery does support arbitrary protocols, we probably need some flag/heuristic to understand if we can reuse what ASP.NET Core gave us or should force `Extract()`. 

I guess the easiest way to fix it is to check if `this.Tracer.TextFormat` is the instance of `OpenTelemetry.Context.Propagation.TraceContextFormat` (W3C Trace-Context implementation) and force extraction otherwise.

The same logic probably needs to be applied on the HttpClient side 

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Collector.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs#L86..L89
