### ISSUE TITLE
AddHttpClientInstrumentation not setting ParentId to Service

### ISSUE THREAD

**Issue by sunildatla** [open-telemetry/opentelemetry-dotnet#3649]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).
Hi , 

I was going through the OpenTelemetry dotnet examples and when i tried this (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/InstrumentationWithActivitySource.cs) locally , i expected that the ParentId of the service spans get the spanid of the client (which it is passing in traceparent header -atleast the trace) , when i see the result the Service is not having any parentid for its span even after adding AddHttpClientInstrumentation like in example . 

What am  i missing?  Isnt Span Context Propogation automated when we use these libraries or do we need to do something manual to extract the span or trace from the http headers and hook them up to the service 

![image](https://user-images.githubusercontent.com/9716121/189770618-53058a11-5707-4ceb-8357-73fb15b65342.png)

**Comment by vishweshbankwar** [comment]
@sunildatla - Your expectation is correct. However, the server side needs to use that injected `traceparent` to start new Activity. That is missing [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/11c804ac6825b9fe39ae1ae73af27434e1a891e1/examples/Console/InstrumentationWithActivitySource.cs#L68-L70). That is the reason you do not see `ParentSpanId` for it.

@cijothomas - is this ^ intentional?

**Comment by vishweshbankwar** [comment]
Just looked at it again - Example is working as intended. @sunildatla Since you modified the example by adding  `AddHttpClientInstrumentation` you would also need to update the Server side as per my comment above. For libraries such as ASP.NET Core, ASP.NET etc. you won't have to do that if you use the instrumentation libraries.
