### ISSUE TITLE
[OpenTelemetry.Exporter.Prometheus] compatibility with .netstandard 2.1

### ISSUE THREAD

**Issue by SilkeP** [open-telemetry/opentelemetry-dotnet#3931]
# Feature Request

**Is your feature request related to a problem?**

I noticed that the nuget package OpenTelemetry.Exporter.Prometheus can't be used in a project targeting .netstandard 2.1.

Package 'OpenTelemetry.Exporter.Prometheus 1.3.0-rc.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.1'. This package may not be fully compatible with your project.	

**Describe the solution you'd like:**

Is there any chance to make it compatible?

**Comment by Kielek** [comment]
I would not expect any further releases for these package. Since 1.4.0(beta) it was split into https://www.nuget.org/packages/OpenTelemetry.Exporter.Prometheus.AspNetCore and https://www.nuget.org/packages/OpenTelemetry.Exporter.Prometheus.HttpListener

HttpListener supports netstandard2.0 (and 2.1). Keep in mind that it is recommended only for dev/testing purposes: https://www.nuget.org/packages/OpenTelemetry.Exporter.Prometheus.HttpListener/1.4.0-beta.3#supportedframeworks-body-tab

**Comment by cijothomas** [comment]
Closing old issue without new activity.
