### ISSUE TITLE
Export Processors should be added last in the list of processors

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet#4013]
# Feature Request

I am not really sure whether this request should go into Spec or to the implementation here so adding to this repo for now. Also, this could either be considered a bug or a feature request so raising it as Feature request for now.

**Is your feature request related to a problem?**

Currently when configuring processors they are added in the order in which they are added. Export processors are special kind of processor that exports the logs/traces/metrics to the desired target. Today when configuring the processors if a user adds a processor after an export processor then that processor will get invoked after the export processor. This leads to a problem where if a processor needs to add/modify certain attributes of the telemetry data before it gets exported then the user must ensure the ordering. If developer ends up adding their custom processor after the export processor then it will just lead to missing the updates done by processor in the exported data.

**Describe the solution you'd like:**
Export processor are special processors and should always be added at the end of the list of processors regardless of the order in which the developer added them. The relative ordering can however be maintained.

**Describe alternatives you've considered.**

There isn't any alternative then developers ensuring the correct order always.

## Additional Context

Add any other context about the feature request here.

**Comment by dpk83** [comment]
@reyang

**Comment by reyang** [comment]
Here is my thinking:
1. From usage scenario, there are indeed requirements for having some processors running before or after exporters.
2. The proposal makes me worried about opening a Pandora's box, which gives many future problems such as "provide a mechanism for a processor to be added at the very beginning of the chain", "provide a mechanism for a processor to be added right after a user specified processor", "move a processor from the head to the tail of the chain" - essentially we'll end up inventing something similar to DOM API.
3. I believe any dependency injection mechanism should/must have thought about the ordering issue, I think we should explore this path first.
4. If it turns out that we want to manipulate the order, I suggest doing more with CompositeProcessor, for example:

```csharp
var cp = new CompositeProcessor();
providerBuilder.AddProcessor(A)
        .AddProcessor(cp) // this is essentially a placeholder which allows future processors to be added at the exact place
        .AddProcessor(B)
        .AddExporter(C)
        .Build();

cp.AddProcessor(myAdditionalProcessorX);
cp.AddProcessor(myAdditionalProcessorY);
```
