### ISSUE TITLE
Improve DI friendliness of Logging

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet#4014]
# Feature Request

**Is your feature request related to a problem?**

- Today Logging extensions provide `AddOpenTelemetry` extension on `ILoggingBuilder`, however `AddProcessor` and `SetResourceProvider` extensions are exposed on `OpenTelemetryLoggerOptions`. This is restrictive for services which are primarily using DI. Exposing these extensions on `OpenTelemetryLoggerOptions` and not on `ILoggingBuilder` and/or `IServiceCollection` limits the ability for third party libraries to provide easier capabilities for adding processor for example, or to compose the resource provider from resources exposed by multiple third party libraries etc. With the DI based mechanism a processor can then be added which can get access to other objects via DI injection and making the APIs really DI friendly for users
- Another ask here is to also expose an override for the existing `AddOpenTelemetry` extension to take in options via 

**Describe the solution you'd like:**

Expose the extensions `SetResourceProvider` and `AddProcessor` on `ILoggingBuilder`.
```csharp
public static ILoggingBuilder AddProcessor<T>(this ILoggingBuilder builder)
            where T : BaseProcessor<LogRecord>{}

public static ILoggingBuilder SetResourceBuilder(this ILoggingBuilder loggingBuilder, ResourceBuilder resourceBuilder);
```

Add another overload for `AddOpenTelemetry` extension
```csharp
public static ILoggingBuilder AddOpenTelemetry(this ILoggingBuilder builder, IConfigurationSection configurationSection) {}
```

**Describe alternatives you've considered.**

Currently we had to implement custom LoggerProvider to get the right functionality

## Additional Context

We would like to move to directly using OpenTelemetryLogger and extending it as opposed to having our own implementation of LoggerProvider and Logger.

**Comment by dpk83** [comment]
@reyang Just raising the ask here for tracking purpose. We have the proposed changes that we can discuss in January.

**Comment by CodeBlanch** [comment]
A couple thoughts on this...

* RE: Options, FYI one change that will make it into 1.4.0 is [this line](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1c69788184befa628e5833439467fbb55b7d2b94/src/OpenTelemetry/Logs/OpenTelemetryLoggingExtensions.cs#L63-L64) which automatically binds logging options to the OTel options class. [I updated the example to use this as well](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1c69788184befa628e5833439467fbb55b7d2b94/examples/AspNetCore/appsettings.json#L6-L10). Maybe that will be useful for some of your cases?

* RE: DI, much effort went into making this possible (eg #3504) but ultimately none of it made it into 1.4.0 😢 The reason for this is OTel spec looks likely to introduce a `LoggerProvider` and `Logger` into the API. There is a branch `main-logs` where I have moved this work. @dpk83 let's chat offline about how we can combine our efforts on this?

**Comment by julealgon** [comment]
> A couple thoughts on this...
> 
> * RE: Options, FYI one change that will make it into 1.4.0 is [this line](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1c69788184befa628e5833439467fbb55b7d2b94/src/OpenTelemetry/Logs/OpenTelemetryLoggingExtensions.cs#L63-L64) which automatically binds logging options to the OTel options class. [I updated the example to use this as well](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1c69788184befa628e5833439467fbb55b7d2b94/examples/AspNetCore/appsettings.json#L6-L10). Maybe that will be useful for some of your cases?

@CodeBlanch that doesn't help with `OtlpExporterOptions` though... That one is currently manually instantiated by the logger version of `AddOtlpExporter`, and relies solely on environment variables to create the options instance (that's a _really_ bad practice folks....):

https://github.com/open-telemetry/opentelemetry-dotnet/blob/690f7e5bbcf2cbcaba47b595b16446ac628377b9/src/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs/OtlpLogExporterHelperExtensions.cs#L58

https://github.com/open-telemetry/opentelemetry-dotnet/blob/690f7e5bbcf2cbcaba47b595b16446ac628377b9/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L60-L61

This basically means I have to do this nasty workaround here, since I'm not reading `OTEL_EXPORTER_OTLP_ENDPOINT` from an envvar on this project, but from a different configuration source:

```csharp
IHost host = Host.CreateDefaultBuilder(args)
    ...
    .ConfigureLogging((context, logging) => 
    {
        // HACK:
        // Force the OTEL endpoint envvar to be populated even if the value is already provided through other
        // configuration means.
        //
        // The OTEL exporter for logs only looks at actual environment variables currently instead of fetching the value
        // from any configuration source like the metrics and traces stacks do.
        // 
        // Since we rely solely on Azure AppConfiguration for settings, we don't provide the 'OTEL_EXPORTER_OTLP_ENDPOINT'
        // as an environment variable, but as a global setting in AppConfiguration. That works as expected for metrics and traces,
        // but is ignored by the logs exporter in its current incarnation.
        // 
        // More information:
        // https://github.com/open-telemetry/opentelemetry-dotnet/issues/4014
        SetOtelExporterEndpointEnvironmentVariable(context);

        logging.AddOpenTelemetry(c => c
            .SetResourceBuilder(...)
            .AddOtlpExporter());
    })

...

static void SetOtelExporterEndpointEnvironmentVariable(HostBuilderContext context)
{
    const string otelExporterEndpointVariableName = "OTEL_EXPORTER_OTLP_ENDPOINT";
    var endpoint = context.Configuration[otelExporterEndpointVariableName];
    Environment.SetEnvironmentVariable(otelExporterEndpointVariableName, endpoint);
}
```

I'd strongly recommend moving away from this approach of setting the default values like that, and into a proper `IConfigureOptions` implementation.

It goes without saying that an options model should be a simple POCO object with no logic like that.

**Comment by CodeBlanch** [comment]
@julealgon I don't disagree with you at all 😄 I'm hoping to clean up logging in 1.6 so it has the same surface as metrics & logs. Just waiting on the OTel spec for logging to go stable. That process is moving slowly, but moving!

If you want to unblock yourself _right now_ (on 1.4) try something like this...

```csharp
// Register OpenTelemetryLoggerProvider
appBuilder.Logging.AddOpenTelemetry(options => options.AddOpenTelemetry(c => c.SetResourceBuilder(...));

// Add OtlpExporter once ServiceProvider is availalble
appBuilder.Services.AddOptions<OpenTelemetryLoggerOptions>().Configure<IServiceProvider>((options, sp) =>
{
    var config = sp.GetRequiredService<IConfiguration>();
    options.AddOtlpExporter(otlpExporterOptions =>
    {
        var endpoint = config.GetValue<string?>("OpenTelemetry:Endpoint", null);
        if (endpoint != null)
        {
            otlpExporterOptions.Endpoint = new Uri(endpoint);
        }
    });
});
```

**Comment by julealgon** [comment]
> @julealgon I don't disagree with you at all 😄 I'm hoping to clean up logging in 1.6 so it has the same surface as metrics & logs. Just waiting on the OTel spec for logging to go stable. That process is moving slowly, but moving!

Any estimate on how long that could take? I'm asking because this particular setup hack here is fairly nasty and I have a few projects that will be potentially affected by it coming up as we want to move away from environment variables and into Azure AppConfiguration for these types of global settings.

Would be nice if there was an overload of `AddOpenTelemetry` on the logger in the meantime that took an `IConfiguration` for example, as that could completely resolve this by just passing that `IConfiguration` along into the `new OtlpExporterOptions` constructor. I can't do that from user code otherwise I would.

With such overload, my code would become this:
```csharp
IHost host = Host.CreateDefaultBuilder(args)
    ...
    .ConfigureLogging((context, logging) => 
    {
        logging.AddOpenTelemetry(context.Configuration, c => c
            .SetResourceBuilder(...)
            .AddOtlpExporter());
    })

...
```
Or maybe this if you opted into passing it into the `AddOtlpExporter` method itself:
```csharp
IHost host = Host.CreateDefaultBuilder(args)
    ...
    .ConfigureLogging((context, logging) => 
    {
        logging.AddOpenTelemetry(c => c
            .SetResourceBuilder(...)
            .AddOtlpExporter(context.Configuration));
    })

...
```
I imagine none of those options needs the log spec to stabilize and could be done temporarily? It is not perfect but it is vastly superior than what I have now.

> If you want to unblock yourself _right now_ (on 1.4) try something like this...
> 
> ```cs
> // Register OpenTelemetryLoggerProvider
> appBuilder.Logging.AddOpenTelemetry(options => options.AddOpenTelemetry(c => c.SetResourceBuilder(...));
> 
> // Add OtlpExporter once ServiceProvider is availalble
> appBuilder.Services.AddOptions<OpenTelemetryLoggerOptions>().Configure<IServiceProvider>((options, sp) =>
> {
>     var config = sp.GetRequiredService<IConfiguration>();
>     options.AddOtlpExporter(otlpExporterOptions =>
>     {
>         var endpoint = config.GetValue<string?>("OpenTelemetry:Endpoint", null);
>         if (endpoint != null)
>         {
>             otlpExporterOptions.Endpoint = new Uri(endpoint);
>         }
>     });
> });
> ```

Well yeah, that would also work. But I almost feel like what I have there ends up being simpler and also works.

Also, you don't need to have the indirection with `IServiceProvider` there. The idea behind the DI-enabled overload of `Configure` is precisely to avoid needing to manually grab instances yourself. This works just fine for example:
```csharp
appBuilder.Services.AddOptions<OpenTelemetryLoggerOptions>().Configure<IConfiguration>((options, config) =>
{
    options.AddOtlpExporter(otlpExporterOptions =>
    {
        var endpoint = config.GetValue<string?>("OpenTelemetry:Endpoint", null);
        if (endpoint != null)
        {
            otlpExporterOptions.Endpoint = new Uri(endpoint);
        }
    });
});
```

**Comment by CodeBlanch** [comment]
> Any estimate on how long that could take?

Rought estimate at the moment is 1.6 around 11/2023.

> Also, you don't need to have the indirection with IServiceProvider there. The idea behind the DI-enabled overload of Configure is precisely to avoid needing to manually grab instances yourself.

Sure but this issue is about general DI support in logging so I decided to show a more general case 😄

> Would be nice if there was an overload of AddOpenTelemetry on the logger in the meantime that took an IConfiguration for example

I don't see a lot of value in this, TBH. `OpenTelemetryLoggerOptions` are today automatically bound to the `Logging:OpenTelemetry` section. [That is done here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/869dccee150547cb8545eca38e29100b115382d4/src/OpenTelemetry/Logs/OpenTelemetryLoggingExtensions.cs#L63-L64).

> Or maybe this if you opted into passing it into the AddOtlpExporter method itself:

I think adding overloads like this inside of OtlpExporter...

```csharp
        public static OpenTelemetryLoggerOptions AddOtlpExporter(
            this OpenTelemetryLoggerOptions loggerOptions,
            IConfiguration configuration) {}

        public static OpenTelemetryLoggerOptions AddOtlpExporter(
            this OpenTelemetryLoggerOptions loggerOptions,
            Action<OtlpExporterOptions> configure) {}
```

...would totally be doable in 1.5. [I'm doing similar over here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/6f657e4750698ef47a72c184a5b5fb8cd591e64f/src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorOpenTelemetryLoggerOptionsExtensions.cs#L105). BUT would you open a dedicated issue for that?

**Comment by julealgon** [comment]
> Rought estimate at the moment is 1.6 around 11/2023.

Oof.. .that's a long ways off... waiting until .NET 8 would be less than ideal for us.

> Sure but this issue is about general DI support in logging so I decided to show a more general case 😄

Fair enough.

> I think adding overloads like this inside of OtlpExporter...
> 
> ```cs
>         public static OpenTelemetryLoggerOptions AddOtlpExporter(
>             this OpenTelemetryLoggerOptions loggerOptions,
>             IConfiguration configuration) {}
> 
>         public static OpenTelemetryLoggerOptions AddOtlpExporter(
>             this OpenTelemetryLoggerOptions loggerOptions,
>             Action<OtlpExporterOptions> configure) {}
> ```
> 
> ...would totally be doable in 1.5. [I'm doing similar over here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/6f657e4750698ef47a72c184a5b5fb8cd591e64f/src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorOpenTelemetryLoggerOptionsExtensions.cs#L105). 

As long as the overload respects the global variable identifiers by passing the `IConfiguration` into the `OtlpExporterOptions` model (or equivalent logic in case refactoring is done), I'm totally ok with this.

Also, if you don't mind me asking, what is the timeline for 1.5?

> BUT would you open a dedicated issue for that?

I can definitely create a dedicated issue for this problem. Look for it by EOD today. Will link with this one for traceability.

**Comment by CodeBlanch** [comment]
@julealgon We have these [milestones](https://github.com/open-telemetry/opentelemetry-dotnet/milestones) defined you can watch but the idea with 1.5 is to get it out in the summer.
