### ISSUE TITLE
Make LogRecord StateValues list mutable

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet#4015]
# Feature Request

**Is your feature request related to a problem?**

Recently `LogRecord` was updated to support mutability. As part of that one can write a processor and mutate the `LogRecord` object to extend the Logging functionality. In that change while the StateValue object itself is mutable i.e. supports completely replacing the StateValue with another list, it is actually a IReadOnlyList which limits adding additional values to the list. More often than not the requirements when modifying the StateValues object is to add to the existing list that to completely replace the list. 

While the same can be achieved by "creating a new list, copying over all fields form existing to new list, adding the new required attributes to the list and then setting the new list as the StateValues", this method is highly inefficient. 

**Describe the solution you'd like:**

I would like the type of StateValues to be changed from IReadOnlyList to IList so new items can be added to it.

**Describe alternatives you've considered.**

The alternative is to create a new list and replace the existing list with new list which is highly inefficient, so we don't want to do that.
Another alternative to write custom logger and log provider so the functionality from processors can be executed before creating the `LogRecord` object so the list can be augmented with required information and set efficiently.

## Additional Context

Add any other context about the feature request here.

**Comment by dpk83** [comment]
@reyang

**Comment by reyang** [comment]
I don't feel we're ready to open this Pandora's box at this moment.
The readonly list is not created by OpenTelemetry SDK, making it mutable comes with both programming model risks and performance costs:
1. if the underlying list is actually mutable, changing it from a telemetry SDK might cause side effect to the data user passed in (considering that the data passed in might be used later for other purposes such as business logic).
2. if the SDK is going to travel through the readonly list and create a general purpose mutable list, it is essentially ruining ILogger's overall direction of "zero-alloc".
3. such enrichment desire seems to be very common for ILogger/Logging.Extensions, I feel we should explore if this is something .NET will support.

For now, my suggestion is that:
1. OpenTelemetry should not make the change
2. The consumer of OpenTelemetry can take the readonly list, and replace it with another list. If performance is the concern, I would suggest that instead of allocating and maintaining a real/physical list, maintaining a virtual/fake one which references the original list by applying special logic to the iterator.
