### ISSUE TITLE
Code style configuration

### ISSUE THREAD

**Issue by alexeyzimarev** [open-telemetry/opentelemetry-dotnet#410]
This project uses code style guidelines that seem to pay a lot of attention to  XML comments, the order of private vs public, properties vs methods and spaces before and after curly braces.

But there's no guideline that concerns the actual _code_, not how it's formatted. It creates a lot of confusion. Using `this` seems to be the standard although that's the first .NET project that I've seen since the 90's that uses such a verbose notation. Using `var` and explicit type declaration, using curly braces and return vs arrow functions for one-lines, and so on - it's all mixed.

Is it possible to come up with better guidelines that would be closer to real life and also set some specific code styling rules that will be easy to follow? I can refer to MassTransit dotSettings file  https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit.sln.DotSettings or even EntityFramework Core .editorconfig file https://github.com/aspnet/EntityFrameworkCore/blob/master/.editorconfig

**Comment by bruno-garcia** [comment]
@alexeyzimarev The repo has a [.editorconfig](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/.editorconfig). One caveat with it is that [VSCode/OmniSharp](https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/), [Rider](https://www.jetbrains.com/help/rider/Using_EditorConfig.html), and [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) all support a different set of properties AFAIK and it's all to help you put/write code "the right way" but at the end it turns into warnings anyway.

`DotSettings` assumes one uses Rider or ReSharper so IMO shouldn't be a requirement for taking contributions.

Ideally we'd use an auto formatter like Rust's [Clippy](https://github.com/rust-lang/rust-clippy) and Gradle/Maven [spotless](https://github.com/diffplug/spotless).

Having used these, it's very upsetting to have a broken build because braces are positioned in the wrong place. Ideally the tool would simply move it to the right place before compiling.

There's [dotnet/codeformatter](https://github.com/dotnet/codeformatter) for that but I personally never used.

It would be great to experiment with _codeformatter_ and hopefully it makes writing code in this codebase easier.

**Comment by bruno-garcia** [comment]
Digging a bit on codeformatter, it seems abandoned. [One issue](https://github.com/dotnet/codeformatter/issues/267) has such note:

> This isn't a supported tool or product. 

Last commend points to [dotnet-format](https://github.com/dotnet/format).

**Comment by eddynaka** [comment]
A quick update....
- We enabled a workflow that will use `.editorconfig` using `dotnet-format` to validate
- We enabled the StyleCopAnalyzer that will use `.ruleset` using `dotnet build` to validate

I think we can close this.

@cijothomas  @reyang
