### ISSUE TITLE
What is the current protocol in deciding what TFM to use for a project?

### ISSUE THREAD

**Issue by Yun-Ting** [open-telemetry/opentelemetry-dotnet#4591]
**Problem**
We currently are relying on the fact of [target framework and its implemented .NET standard version](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#latest-versions) when building projects with dependencies and the TFMs of the projects don't match.
This can introduce conflicts in some situations, for example, https://github.com/open-telemetry/opentelemetry-dotnet/pull/4460#discussion_r1195868228

While exploring different alternatives (https://github.com/open-telemetry/opentelemetry-dotnet/pull/4580#issuecomment-1589750091) to bring in AOT attributes to the repo, I notice currently there is no clear guideline on how to decide the TFM of a project.

**Proposal**
Make TFMs consistent across different projects; for example, https://github.com/open-telemetry/opentelemetry-dotnet/pull/4370. Retire the TFM when it's out of support across all projects. The engineering overhead I foresee to achieve the goal is insignificant (mainly in maintaining public API docs.)

**Comment by vitek-karas** [comment]
I think it's fair to say that most of the problems observed are due to the heavy usage of `InternalsVisibleTo` which seems to be the norm in this project (I can't comment on why that is). The `InternalsVisibleTo` make the typical patterns on how to handle various TFMs and multi-targeting much more complex.

For the trim/AOT compatibility effort, it would make things definitely simpler if all project targeted the same set of TFMs. But I don't know the reason why the TFMs are setup the way they are, so I can't really comment on potential disadvantages.

**Comment by eerhardt** [comment]
We did a similar effort in dotnet/runtime for our libraries that shipped as NuGet packages. All the libraries have a consistent set of TFMs across the board. For example, for the .NET 8 release, that set is: `net8.0;net7.0;net6.0;netstandard2.0;net462`. (The set used in OTel would be different - I'm not suggesting to use the same set as dotnet/runtime does). The set changes as TFMs go out of support. Using a consistent set across all libraries in the repo makes working in the repo a lot easier as every library has the same set.

You can read about the pros and cons at:

* https://github.com/dotnet/runtime/issues/54012
* https://github.com/dotnet/runtime/issues/54012#issuecomment-858957392

@ViktorHofer, do you have any suggestions in this area for other library authors? In my point of view, the advantages clearly outweigh the disadvantages.
