### ISSUE TITLE
Use file scoped namespaces

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet#4640]
Update the code files in the repo to use file scoped namespaces: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

This should be done in smaller PRs each preferably targeting three to four `src` projects and their corresponding `test` projects in one PR.

**Comment by utpilla** [comment]
@kyle-lt Thanks for offering your help! Feel free to send the PRs.

**Comment by kyle-lt** [comment]
Great, thanks @utpilla , can you pls assign me and I'll start to chip away?

**Comment by kyle-lt** [comment]
PR #4654 only covered the core OpenTelemetry src and test project, so we may want to keep this issue open until all of the projects are covered. I’ll knock that out in a few more PRs. --Kyle TullyOn Jul 13, 2023, at 5:50 PM, Utkarsh Umesan Pillai ***@***.***> wrote:﻿
Closed #4640 as completed via #4654.

**Comment by utpilla** [comment]
@kyle-lt This issue got closed because the PR description had "Fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/4640" in it. Could you use another term instead of "Fixes" such as "Towards https://github.com/open-telemetry/opentelemetry-dotnet/issues/4640" in the PRs going forward.

**Comment by kyle-lt** [comment]
I changed it to “Partially” Fixes…But, clearly that didn’t do the trick, apologies for the nuisance. I’ll make sure to use your suggested wording in the subsequent PRs. Thanks!--Kyle TullyOn Jul 13, 2023, at 6:12 PM, Utkarsh Umesan Pillai ***@***.***> wrote:﻿
@kyle-lt This issue got closed because the PR description had "Fixes #4640" in it. Could you use another term instead of "Fixes" such as "Towards #4640" in the PRs going forward.

**Comment by jarosal** [comment]
@utpilla first PR! #4680

**Comment by jarosal** [comment]
Hi @utpilla,
I've created PRs for all of the remaining projects/folders in this repo. After they are merged I think you should merge #4716 so all of the future files use this convention.

**Comment by utpilla** [comment]
Thank you @kyle-lt and @jarosal for working on this!
