### ISSUE TITLE
Reconsider Moq usage because of privacy issues

### ISSUE THREAD

**Issue by lachmatt** [open-telemetry/opentelemetry-dotnet#4758]
Reconsider usage of `Moq` because of privacy issues described https://github.com/moq/moq/issues/1372.
For reference, `Moq` was replaced with `NSubstitute` in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2816

**Comment by Kielek** [comment]
Notes from August 15 sig meeting:
* No action necessary today since the version we use is prior to Moq adding SourceLink dependency.
* SourceLink has been removed in the latest release suggesting the maintainer is responsive to the community https://github.com/moq/moq/releases/tag/v4.20.69.
* If we do consider removing our use of Moq, we should consider attempting to eliminate using a mock library completely instead of replacing it with an alternative. Potentially a “good first issue/help wanted”.

**Comment by Kielek** [comment]
@ngruson, great job here. Do you have a plan to make similar changes in https://github.com/open-telemetry/opentelemetry-dotnet-contrib ?

**Comment by ngruson** [comment]
Hi @Kielek ,
I certainly can have a look in a couple of days if you want.

**Comment by Kielek** [comment]
It will be great! Thanks!
