### ISSUE TITLE
IncludeStateTrace internal ?

### ISSUE THREAD

**Issue by yassinebennani** [open-telemetry/opentelemetry-dotnet#4888]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).

Hello Guys,

Can someone please explain to me what is the reason behind defining the property IncludeStateTrace of the class OpenTelemetryLoggerOptions as internal and not public ?

Thank you

**Comment by Kielek** [comment]
See PR: #4334

especially https://github.com/open-telemetry/opentelemetry-dotnet/pull/4334#discussion_r1170672257

Nobody make a request/pr for that.

**Comment by CodeBlanch** [comment]
@yassinebennani We removed it from the public API because we were unsure on the use case and if it was really useful/needed. You want to include trace state on your logs? Can you provide a little detail about the why? I'm interested in how you plan to use that data and why it would be helpful to have.
