### ISSUE TITLE
ZipkinTraceExporter DoPostAsync method

### ISSUE THREAD

**Issue by brunosantosfarfetch** [open-telemetry/opentelemetry-dotnet#489]
I was going through OpenTelemetry code checking some implementation details and found this:

```csharp
private async Task DoPostAsync(HttpClient client, HttpRequestMessage request)
{
      using (var response = await client.SendAsync(request).ConfigureAwait(false))
      {
            if (response.StatusCode != HttpStatusCode.OK &&
                response.StatusCode != HttpStatusCode.Accepted)
            {
                 var statusCode = (int)response.StatusCode;
            }
      }
}
```
It seems that both the `if` statement and the `var` declaration are done but don't add any value and could be removed. Is my understanding correct? If so I am more than willing to remove it.

**Comment by MikeGoldsmith** [comment]
Hi @brunosantosfarfetch

You're correct - the `if` and `var` are redundant in this case because the statusCode is not used.

An alternative to checking status codes manually is to use the [EnsureSuccessStatusCode](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode) on the `response` object. This throws an exception if a non 2XX response is received. Though I'm unsure what repercussions there would be here.

**Comment by brunosantosfarfetch** [comment]
I think throwing an exception will cause a behavioural braking change. It's probably better to remove the redundant lines of code

**Comment by MikeGoldsmith** [comment]
Yeah, that's a good first step. I'm not familiar with the code, but I would assume whomever created this method expected to do something with the status code, and likely want to report failed requests.

**Comment by eddynaka** [comment]
Hi all, is this issue still available?

If yes, can I take it?

If yes, should I just remove the if and var lines?


Thanks!

**Comment by SergeyKanzhelev** [comment]
@eddynaka yes, go ahead!
