### ISSUE TITLE
Unable to set RequestFilter for AspNetCore RequestCollector in the AspNetCoreCollectorOptions

### ISSUE THREAD

**Issue by tomstreet** [open-telemetry/opentelemetry-dotnet#493]
Is there a reason that the `RequestFilter` property on `AspNetCoreCollectorOptions` is internal? I was looking for a way to apply a filter to the RequestCollector based on the request path and stumbled across this. It looks like it is all wired up internally but isn't publicly exposed thus can't be used.

I was hoping to be able to do something like:
`services.AddRequestCollector(o => o.RequestFilter = ctx => ctx.Request.Path != "some/url")`

Is there another way this can be achieved? Or can we just make `RequestFilter` public?
Happy to submit a PR with this change if it's that simple...?

**Comment by lmolkova** [comment]
This API is not exposed because it's probably not final shape for it and we don't want to expose it until we have a consistent story for filtering across different integrations.
Also, filtering before collection is not common OpenTelemetry concept (while definitely good for perf!)

You can still do it by implementing some custom filtering `SpanProcessor`. Check out the example here https://github.com/open-telemetry/opentelemetry-dotnet#advanced-configuration

**Comment by tomstreet** [comment]
Thanks for the clarification and guidance.

I like how the processor pipeline provides a standardised way of plugging in extra functionality, so the collector doesn't need to worry and can just focus on collecting. It would be nice to have a simple API exposed, like that `RequestFilter`, to allow access purely in the name of perf so at least the option is there. I guess it would have to be specific to each collector config.
