### ISSUE TITLE
Program cannot access a public API at runtime

### ISSUE THREAD

**Issue by AB027PS** [open-telemetry/opentelemetry-dotnet#4970]
# Bug Report

I'm using OpenTelemetry 1.6.0-rc.1

This is happening on all .NET Framework versions older than 4.8.1, but not on any .NET core versions.

## Symptom

The program fails at runtime when I invoke the method Sdk.CreateLoggerProviderBuilder with this error
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/124600946/16037c9c-f503-41f3-95ec-1722e74d1fa0)
even though it compiles fine. I'm using an experimental version of the package, so the access modifier of the method is set to public.

## Reproduce

Create a new console application which targets a .NET framework version older than or equal to 4.8.1 and invoke the method Sdk.CreateLoggerProviderBuilder. This also happens if I try to create an instance of a class which inherits ExemplarFilter, so presumably this affects all APIs where access modifiers are decided by EXPOSE_EXPERIMENTAL_FEATURES.

**Comment by CodeBlanch** [comment]
I'll take a look at this.

**Comment by CodeBlanch** [comment]
@AB027PS @juliuskoval 

I just did this:

ConsoleApp.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.6.0-rc.1" />
  </ItemGroup>
</Project>
```

Program.cs:

```csharp
using OpenTelemetry;
using OpenTelemetry.Logs;

using var provider = Sdk.CreateLoggerProviderBuilder()
    .Build();

Console.WriteLine("Hello, World!");
```

Everything works fine.

If I change the project file a little bit to be more interesting...

ConsoleApp.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.6.0-rc.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNet" Version="1.6.0-beta.2" />
  </ItemGroup>
</Project>
```

I can no longer build at all.

The reason for that is `OpenTelemetry.Instrumentation.AspNet` brings in `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule` which brings in `OpenTelemetry.Api` v1.6.0 which does NOT have the experimental APIs public.

So my question is: What other packages are you referencing? And what do your binding redirects in Web.config/App.config look like?

My guess would be there is a redirect thing going on if this is a runtime break but if you can provide me a little more information I can try to provide some recommendations for how to make it work.

PS: Since this issue was posted we now have `1.7.0-alpha.1`. Switching to that in my example above makes it work because `1.7.0-alpha.1` is newer than all `1.6.0*` bits. But the issue may reappear once there are packages looking for stable `1.7.0` things.

```xml
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.7.0-alpha.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNet" Version="1.6.0-beta.2" />
  </ItemGroup>
```

**Comment by juliuskoval** [comment]
Hi,

I created a .NET Framework 4.8 console application and only added this package reference `<PackageReference Include="OpenTelemetry" Version="1.6.0-rc.1" />`.
Then in the Main method the only thing I did was call the `Sdk.CreateLoggerProviderBuilder` method and I didn't use any binding redirects. Weirdly enough it worked when I retested it on another PC, so it might not be an issue with the package itself.

**Comment by CodeBlanch** [comment]
@juliuskoval Are you by chance also running the [OpenTelemetry .NET Automatic Instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation#opentelemetry-net-automatic-instrumentation) app on the failing boxes? It installs things into the GAC which may also cause havoc at runtime.

**Comment by juliuskoval** [comment]
Not right now, although I as playing around with it for a while, so that might be it.

**Comment by AB027PS** [comment]
I correctly uninstalled .NET automatic instrumentation and that solved the issue.
