### ISSUE TITLE
Make OtlpLogExporter public

### ISSUE THREAD

**Issue by AB027PS** [open-telemetry/opentelemetry-dotnet#4971]
# Feature Request

I'm trying to create an NLog target which would export logs using the OpenTelemetry protocol. Having access to this class would allow me to create a sort of an internal logger, which would export incoming logs using the existing infrastructure from the OpenTelemetry.Exporter.OpenTelemetryProtocol library.

**Describe the solution you'd like:**

I'd like the OtlpLogExporter class to be made public.

**Describe alternatives you've considered.**

An alternative is instantiating the class using reflection or reimplementing much of the OpenTelemetry.Exporter.OpenTelemetryProtocol library, neither of which is ideal. As far as I know, there isn't a public way to create an instance of OtlpLogExporter .

**Comment by vishweshbankwar** [comment]
@AB027PS Thanks for raising this. Would you be interested in sending the PR for change?

@open-telemetry/dotnet-maintainers FYI

**Comment by cijothomas** [comment]
Even if the Exporter is made public, how do you intend to use this? If your goal is to nlog -> Otel, then [this](https://github.com/open-telemetry/opentelemetry-dotnet/issues/4433) is probably what you want?

**Comment by snakefoot** [comment]
According to OpenTelemetry own [documentation](https://opentelemetry.io/docs/collector/), then one is encouraged to use a Collector, instead of sending directly.
> In general we recommend using a collector alongside your service, since it allows your service to offload data quickly and the collector can take care of additional handling like retries, batching, encryption or even sensitive data filtering.

Thus the application is not affected by OpenTelemetry-connectivity-downtime, and application doesn't have to know about OpenTelemetry-connection-details.

Could be nice if the [FileLog](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver)-Receiver had an official Json-Schema, that required minimum parsing. Then it would "just" be a matter of configuring NLog to write to a JSON-file.

**Comment by juliuskoval** [comment]
@cijothomas I am the same person as AB027PS, only I don't currently have access to that account, so I'll answer this way. 

The repo with the target is work in progress, so I'm not going to make it public yet, but here is a text file with the target, since I couldn't upload a .cs file.
[OtlpTarget.txt](https://github.com/open-telemetry/opentelemetry-dotnet/files/13057601/OtlpTarget.txt)

I'm making use of the bridge API, but the only missing piece is OtlpLogExporter. I also encountered https://github.com/open-telemetry/opentelemetry-dotnet/issues/4970, but that is a separate issue.

**Comment by cijothomas** [comment]
> According to OpenTelemetry own [documentation](https://opentelemetry.io/docs/collector/), then one is encouraged to use a Collector, instead of sending directly.
> 
> > In general we recommend using a collector alongside your service, since it allows your service to offload data quickly and the collector can take care of additional handling like retries, batching, encryption or even sensitive data filtering.
> 
> Thus the application is not affected by OpenTelemetry-connectivity-downtime, and application doesn't have to know about OpenTelemetry-connection-details.
> 
> Could be nice if the [FileLog](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver)-Receiver had an official Json-Schema, that required minimum parsing. Then it would "just" be a matter of configuring NLog to write to a JSON-file.

Not sure how is this related to this issue?

**Comment by snakefoot** [comment]
> @cijothomas Not sure how is this related to this issue?

Only to mention that one is encouraged to use a Collector, instead of sending directly using exporter. Thus details about OpenTelemetry-connectivity-details should not be a concern of the application.
