### ISSUE TITLE
Default host behavior for OpenTelemetryBuilder With* extensions

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#4985]
Related to #4896

See: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4958#issuecomment-1776276235

Currently calling `WithMetrics` or `WithLogging` does NOT enable integration with the hosting pipeline (`ILoggerFactory` or `IMetricsListener`).

Based on discussions with @noahfalk & @samsp-msft it sounds like we want to enable those by default perhaps giving users a way to opt-out. Opening this issue to track that effort.

Updates...

Metrics: #4958 changes `WithMetrics` to register the `IMetricsListener`
Logging: TBD

**Comment by martinjt** [comment]
I think this is an interesting approach, however, a core part of the OpenTelemetry ecosystem is adding instrumentation libraries and opting in. What we're doing here is predicating this on the fact that AspNetCore exists, and therefore adding Meter's for that, or some other things.

Right now, you need to add `OpenTelemetry.Instrumentation.AspNetCore` as a package AND add it to the pipeline to enable it. This seems like we're suggesting to remove those hops in favour of "if you add `.WithMetrics()` you'll get the defaults".

I'm not sure that's the approach we should take here, especially not in a minor release. As soon as someone updates their app, they're going to get a tonne of new metric datapoints, and if they'd not added AspNetCore, process etc. before due to, say, cost at the backend side, they're suddenly going to blow that out.

Logging is more interesting, and I'm not sure about that one, but metrics I don't think we should be adding listeners on anything until someone has opted in.

**Comment by CodeBlanch** [comment]
@martinjt 

Slight clarification. What we're talking about here is enabling the integration, not turning on or listening to anything. If a user calls `services.AddOpenTelemetry().WithMetrics(builder => builder.AddOtlpExporter())` they won't see any metrics unless they take further action. That action could be...

* Calling `AddMeter` to listen via the SDK.
* Add some instrumentation (ex `builder.AddAspNetCoreInstrumentation()`) to the builder (generally it calls `AddMeter` for you) to listen via the SDK.
* Adding configuration under "Metrics" to listen via `IMetricsListener` (new .NET 8 stuff).
* Calling `services.AddMetrics(builder => builder.EnableMetrics(...))` to listen via `IMetricsListener` (new .NET 8 stuff).

Essentially the user still has to opt-in to everything they want to listen to. Does that help?
