### ISSUE TITLE
Question about samplers, null activity and IsAllDataRequested=false

### ISSUE THREAD

**Issue by gao-artur** [open-telemetry/opentelemetry-dotnet#4987]
# Question

The API [Basic usage](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#basic-usage) says

> 3. ....
> If there are no listeners interested in this activity, _the activity above will be null_. This happens when the final application does not enable OpenTelemetry (or other ActivityListeners), or _when OpenTelemetry samplers chose not to sample this activity_. 
> ...
> 4. ...
> IsAllDataRequested is the same as [Span.IsRecording](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#isrecording) and _will be false when samplers decide to not record the activity_,
> ...

Is there any difference between `not to sample this activity` and `not record the activity`? If they are different, what's the difference? If they are same, when the activity will be `null` and when the `IsAllDataRequested` will be `false`?

**Comment by cijothomas** [comment]
Activity will be null, if the final application does not even enable OpenTelemetry. This is done to avoid the heap-allocation as `Activity` is a heap allocated class. 

Once user enables OpenTelemetry (i.e setup TracerProvider and enable a given ActivitySource), then samplers are run. The outcome of sampler determines if the activity is null or not, and if not-null, will it be created with IsAllDataRequested=true, and TraceFlags=set/unset.


The fact that Activity can be null based on sampling decision is a questionable one, and is not aligned with OTel spec. OTel spec says Activity must be created irrespective of Sampler decision. This is tracked as a bug : https://github.com/open-telemetry/opentelemetry-dotnet/issues/3290

**Comment by gao-artur** [comment]
Then, currently, the `IsAllDataRequested` is always `true`? Or it can be set to `false` even when sampler decides to record the activity?

**Comment by cijothomas** [comment]
> Then, currently, the `IsAllDataRequested` is always `true`? Or it can be set to `false` even when sampler decides to record the activity?

Its not always true. Its done based on Sampler's decision! The doc shows what situations true vs false is set for that field:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/SamplingDecision.cs

**Comment by utpilla** [comment]
@gao-artur Here are the possible states of activity and its properties based on the sampler's decision.

| SamplingDecision  | Activity    | Activity.IsAllDataRequested |  Activity.Recorded (used to determine if the sampling bit for W3C Trace Id should be set for downstream propagation) |
| :-------------------- | --------- | ------------------------------ |  -------------------- |
| RecordAndSample |   Not null | True                                     | True                        |
| Record                   |   Not null | True                                     | False                       |
| Drop                      |   Could be null or not null. If the activity being created is a root activity or if its parent is remote, then not null otherwise null | False when activity is not null                                     | False                        |

**Comment by cijothomas** [comment]
ChatGpt, make the above comment and modify the docs :)

**Comment by gao-artur** [comment]
@utpilla Now that makes sense 😄. Thank you for explanation!
