### ISSUE TITLE
[API Proposal]: Add an overload to `OpenTelemetryBuilder.WithLogging` to configure `OpenTelemetryLoggerOptions` only

### ISSUE THREAD

**Issue by joegoldman2** [open-telemetry/opentelemetry-dotnet#5105]
Considering:

```cs
services.AddOpenTelemetry()
    .ConfigureResource(builder =>
    {
        builder.AddAttributes(
            new List<KeyValuePair<string, object>>
            {
                new KeyValuePair<string, object>(ResourceSemanticConventions.AttributeServiceName, "service-name"),
                new KeyValuePair<string, object>(ResourceSemanticConventions.AttributeServiceNamespace, "ns1"),
            });
    })
    .WithLogging(null, options =>
    {
        options.AddOtlpExporter();
    });
```

I'm using `WithLogging` and I only need to configure `OpenTelemetryLoggerOptions`. The ResourceBuilder used by tracing, metrics, and logging is often configured globally using `ConfigureResource` and there is nothing else to configure in the `LoggerProviderBuilder` (the first null argument when calling `WithLogging` in my example).

**Proposed change**

Add a new overload to configure `OpenTelemetryLoggerOptions` only

```diff
namespace OpenTelemetry;

public sealed class OpenTelemetryBuilder
{
+    public OpenTelemetryBuilder WithLogging(Action<OpenTelemetryLoggerOptions> configure)
+    {
+        return WithLogging(configureBuilder: null, configureOptions: configure);
+    }
}
```

**Usage**

```cs
services.AddOpenTelemetry()
    .ConfigureResource(builder =>
    {
        builder.AddAttributes(
            new List<KeyValuePair<string, object>>
            {
                new KeyValuePair<string, object>(ResourceSemanticConventions.AttributeServiceName, "service-name"),
                new KeyValuePair<string, object>(ResourceSemanticConventions.AttributeServiceNamespace, "ns1"),
            });
    })
    .WithLogging(options => // 👈 no need to pass null as a first argument
    {
        options.AddOtlpExporter();
    });
```

**Comment by joegoldman2** [comment]
Probably something similar to do with `public static ILoggingBuilder UseOpenTelemetry(this ILoggingBuilder builder, Action<LoggerProviderBuilder>? configureBuilder, Action<OpenTelemetryLoggerOptions>? configureOptions)` where a new overload with only `Action<OpenTelemetryLoggerOptions>? configureOptions` is very welcome.

**Comment by CodeBlanch** [comment]
@joegoldman2

There are a couple reasons why I didn't add this initially and why I'm hesitant to do it now.

1) The darn compiler!

   If we had these:

   ```csharp
    public OpenTelemetryBuilder WithLogging(Action<LoggerProviderBuilder> configureBuilder) {}
    public OpenTelemetryBuilder WithLogging(Action<OpenTelemetryLoggerOptions> configureOptions) {}
   ```

   When you do this:

   ```csharp
   appBuilder.Services.AddOpenTelemetry().WithLogging(t => { });
   ```

   The compiler will barf:

   `error CS0121: The call is ambiguous between the following methods or properties: 'OpenTelemetryBuilder.WithLogging(Action<LoggerProviderBuilder>)' and 'OpenTelemetryBuilder.WithLogging(Action<OpenTelemetryLoggerOptions>?)'`

   It can't infer which method you intended to call.

   Same reason why we now have `ILoggingBuilder.UseOpenTelemetry` instead of a new overload of `ILoggingBuilder.AddOpenTelemetry` 😄

2) I don't think it is really needed.

   You are probably wanting to do something like this?

   ```csharp
   appBuilder.Services.AddOpenTelemetry().WithLogging(o => {
      o.IncludeScopes = true;
      o.AddOtlpExporter();
   }});
   ```

   I think that is natural given the state we are currently in. But I'm hoping that is a short-lived thing. That is utilizing `OpenTelemetryLoggerOptions.AddOtlpExporter()` which is a flawed API. Hoping it becomes obsolete and at some point goes away.

   @Yun-Ting is working on adding an `AddOtlpExporter` extension on `LoggerProviderBuilder` which will allow for this:

   ```csharp
   appBuilder.Services.AddOpenTelemetry().WithLogging(
     b => b.AddOtlpExporter(),
     o => o.IncludeScopes = true);
   ```

   The future state is `OpenTelemetryLoggerOptions` is only used to configure the `ILogger` switches (`IncludeFormattedMessage`, `IncludeScopes`, etc.). But personally I wouldn't use the `Action<OpenTelemetryLoggerOptions>` at all! You could do this...

   ```csharp
   appBuilder.Services.Configure<OpenTelemetryLoggerOptions>(o => o.IncludeScopes = true);
   appBuilder.Services.AddOpenTelemetry().WithLogging(b => b.AddOtlpExporter());
   ```

   Or just set your options in your logging config!

   ```json
   {
     "Logging": {
       "LogLevel": {
         "Default": "Information"
       },
       "OpenTelemetry": {
         "IncludeScopes": true,
       }
     }
   }
   ```

   ```csharp
   appBuilder.Services.AddOpenTelemetry().WithLogging(b => b.AddOtlpExporter());
   ```

**Comment by joegoldman2** [comment]
Ok, fair enough, I understand. Thank you @CodeBlanch

**Comment by joegoldman2** [comment]
@CodeBlanch should we close this issue?

**Comment by joegoldman2** [comment]
@CodeBlanch should we close this issue?
