### ISSUE TITLE
Add support for Instrument Advisory Parameter for ExplicitHistogram Buckets

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#5166]
Add support for Instrument Advisory Parameter for ExplicitHistogram buckets
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advisory-parameter-explicitbucketboundaries

**Comment by JamesNK** [comment]
PR for annotating ASP.NET Core metrics: https://github.com/dotnet/aspnetcore/pull/56500
Issue for doing the same in dotnet/runtime: https://github.com/dotnet/runtime/issues/104137

As part of this work, opentelemetry-dotnet in .NET 9 or greater should use advisory values instead of the hack here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/978b461771c742ddc11e3c590fe52715af253450/src/OpenTelemetry/Metrics/Metric.cs#L21-L33

**Comment by cijothomas** [comment]
closed via https://github.com/open-telemetry/opentelemetry-dotnet/pull/5854
