### ISSUE TITLE
System.Diagnostic.DiagnosticSource nuget overrides version provided by .NET

### ISSUE THREAD

**Issue by verdie-g** [open-telemetry/opentelemetry-dotnet#5277]
# Bug Report

- OpenTelemetry.Api 1.4.0+
- net6.0

## Symptom

The .NET runtime consists of many dll. For some of them, Microsoft also provides nuget packages so that a runtime with lower version could use some isolated features from the newer runtime. Obviously nothing is guaranteed to work in this case, it could blow up at runtime.

Also, in my company we are currently using a fork of .NET 6 so that we can apply patches in a timely manner. One of our patch affects System.Diagnostics.

We are currently blocked from upgrading from 1.3.X to 1.4.X+ because it targets the nuget System.Diagnostics.DiagnosticSource to 7.0.0 and to 8.0.0 with 1.7.X.

**What is the expected behavior?**

I'm expecting my external dependencies to use the libraries provided by the .NET SDK when possible rather than using their equivalent nuget to avoid:
1. Potential compatibility issues
2. Override custom patches of potential forks

**What is the actual behavior?**

A reference to OpenTelemetry.Api 1.4.0+ overrides our custom System.Diagnostics.DiagnosticSource version.

## Reproduce

1. Create an app targeting .NET 6.0
3. Reference OpenTelemetry.Api 1.4.0+
4. System.Diagnostics version is now 7.0+

**Comment by cijothomas** [comment]
DiagnosticSource latest version is needed in OTel, and that is by-design.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/Directory.Packages.props#L46-L55

**Comment by hdost** [comment]
> DiagnosticSource latest version is needed in OTel, and that is by-design. https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/Directory.Packages.props#L46-L55

Could you explain the design decision here. This makes working with package when you don't have the latest version of the api very difficult. 
It also means that bumping between versions is much harder.

Is there a policy around this? It seems like a breaking change to the API and should at a minimum rev the version of OpenTelemetry. Otherwise this is a poison pill to anyone who has compatibility issues.

**Comment by hdost** [comment]
> The design decision is already explained here:
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/Directory.Packages.props#L46-L55
> 
> _It seems like a breaking change to the API_ 
> 
> Sorry, I don't follow this.. What is the breaking change here? 

This would be the type of breaking change mentioned. 
https://learn.microsoft.com/en-my/dotnet/standard/library-guidance/breaking-changes#behavior-breaking-change

> Adding features and improving bad behaviors is a good thing, but without care it can make it very hard for existing users to upgrade. One approach to helping developers deal with behavior breaking changes is to hide them behind settings. **Settings let developers update to the latest version of your library while at the same time choosing to opt in or opt out of breaking changes.** This strategy lets developers stay up to date while letting their consuming code adapt over time.

Currently you're forcing an update to a library which is a breaking change 6->7->8 of a transitive dependency. That dependency is used for other things and doing this forces code changes across a large code base before being able to take advantage of incremental improvements in your library.

**Comment by cijothomas** [comment]
@hdost Its not clear what is the breaking change you are referring to?

1.  Can you give a concrete example? 
2.  And what is your proposal instead of depending on latest version of DS?

**Comment by verdie-g** [comment]
I noticed that OTEL also forces `Microsoft.Extensions.*` 8.0.0+. We don't plan to use these nugets before migrating to .NET 8. Is that a requirement for OTEL to work? I would expect these nugets to match the target framework version.

**Comment by hdost** [comment]
@cijothomas i think what may be a bit more confidence building is actual policies around how these policies are defined 

Because as @verdie-g mentioned above there's more than just a single library at issue. 

> 3) Since version 3.1.0, the .NET runtime team is holding a high bar for backward compatibility on these packages even during major version bumps, so compatibility is not a concern here.

This is a statement in this repo, but there's no link to a public commitment on these. Our hesitancy towards this is that we just spent a significant amount of effort to upgrade to past 3.1 and it was painful to say the least. We're dealing with thousands of modules across hundreds of repositories. So you'll have to excuse us for not taking the word of a comment in a properties file. 

Is there some sort of policy for public view? Most google searches lead me to nothing of the sort. 

I have seen this similar "high bar language" but aside from a github comment or a line in a config file I'm not seeing anything.
