### ISSUE TITLE
Re-create Span with existing span ID

### ISSUE THREAD

**Issue by RohitRanjanMS** [open-telemetry/opentelemetry-dotnet#5286]
Hi,

We have specific scenarios in Azure Functions where we aim to re-create the Activity with same span ID as the remote span.

In the out-of-process scenario, the SERVER span is generated in the host process, while the user's code is executed in the worker process. Our objective is to conceal the implementation details and explore possibilities for recreating the remote span, thereby invoking the user's code within this context.

In the Durable Functions, the same work undergoes pausing and resuming on the worker. Upon each resumption of the work, our goal is to establish the same span as the current span.

We attempted to utilize reflection for this purpose but are currently exploring whether there is an officially supported method to achieve the desired outcome.

**Comment by RohitRanjanMS** [comment]
@trask @lmolkova @jviau @cijothomas

**Comment by cijothomas** [comment]
There is nothing in the spec that allows to re-create a Span, reusing same SpanId as an existing span, right? 
Even the java example -it does not look like spanid is re-used...

**Comment by lmolkova** [comment]
Java does not re-create span, it creates a current context that can be used a parent.

I.e. functions host will create a span, then context would flow to function worker, where span context can act as an ambient parent.

@RohitRanjanMS to confirm that re-creating full Activity with an existing span-id is not a requirement. 
The requirement (based on my understanding) is to 
- create children from it being ambient
- potentially record attributes/events on this semi-activity and pass them back to the host (this is a future extensibility)

My understanding that it needs BCL work, but we'd like to hear otel-dotnet thoughts on this.

**Comment by cijothomas** [comment]
This is likely to be relevant : https://github.com/dotnet/runtime/issues/86966

**Comment by jviau** [comment]
@cijothomas that is _mostly_ what we need. It is missing one thing we are considering but have not settled on as mandatory: capturing tags in the worker process and flowing back to the host. We would then add those tags to the host's `Activity` before recording it.

Related For the original title of this issue, there is another use case for this: durable task.

Without getting into the implementation details of how durable orchestrations work, suffice it to say that we re-create the same activity multiple times and only want to record it when the orchestration completes. This is because the same "operation" is loaded in and out of the application multiple times through its life ("replayed"). Representing each replay as its own span is noisy a not usable from a customer standpoint. Today we use [reflection](https://github.com/Azure/durabletask/blob/0dff7648b6ec2439520cb0660275e93ae177e8f4/src/DurableTask.Core/Tracing/DiagnosticActivityExtensions.cs#L52) to set the span ID each time we re-hydrate the activity. We don't need to worry about manually persisting and rehydrating tags as the orchestration replay will naturally rehydrate those.

We can discuss this in a separate issue (or even in the dotnet repo?) if need be.

**Comment by cijothomas** [comment]
> @cijothomas that is mostly what we need. 

When you said this, did you meant https://github.com/dotnet/runtime/issues/86966 is what you'll mostly need?

**Comment by jviau** [comment]
> > @cijothomas that is mostly what we need.
> 
> When you said this, did you meant [dotnet/runtime#86966](https://github.com/dotnet/runtime/issues/86966) is what you'll mostly need?

Yes, that issue is mostly what we need. It is only having a way to capture tags and propagate them back to the host that wouldn't be there. But as I said, we are not convinced we will even have a feature like that.

**Comment by cijothomas** [comment]
Then we can close this issue, as this issue is asking for "re-create  Span with existing span id", which is infeasible, and won't be supported without backing spec first.

**Comment by jviau** [comment]
@cijothomas let me clarify: for functions that issue will work for us. For durable task, we do have a need to recreate the same span repeatedly. This framework follows a record -> replay system, so we are replaying customer actions back to them, and part of that involves setting up the same span for them to interact with during the replay.

**Comment by cijothomas** [comment]
> For durable task, we do have a need to recreate the same span repeatedly.

Got it. This should be opened as a spec issue as well.

**Comment by cijothomas** [comment]
Before opening a feature request against this repo, consider whether the feature
should/could be implemented in the [other OpenTelemetry client
libraries](https://github.com/open-telemetry/). If so, please [open an issue on
opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new)
first.

**Comment by martinjt** [comment]
I'm closing this issue as not planned since it would need to be part of the spec if we were going to implement something like this.
