### ISSUE TITLE
Move MeterProvider to API

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#579]
The MeterFactory is currently part of the SDK metrics/Configuration but should be part of the API.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api-user.md#obtaining-a-meter

**Comment by eddynaka** [comment]
@MikeGoldsmith , i started to look at this issue but I got some items that I don't know if it is intentional:
1. with the first move of MeterFactory I had to move many other files as well, such as Aggregators, Configuration, some Export files and filenamesdk.cs inside Meters folder. Is that right?
2. with this movement, many classes started to throw an error based on some xml docs rule. For example, I had to move Aggregator.cs to the OpenTelemetry.Api project, so it started complaining about the methods. Do we have a place with some docs saying what each method do?
3. In the MeterSdk we have the usage of OpenTelemetrySdkEventSource.cs, but that file is in the SDK and it is internal. Do you have any suggestion on this?

Thank you!

**Comment by cijothomas** [comment]
@eddynaka 
Most likely, other classes shouldn't be moved. This is not trivial, as unlike Tracer specs, Meter specs are not complete (eg: No specs abour MetricProcessor exists). So each has to be evaluated individually.

Perhaps you can look into the, renaming MeterFactory to Provider, similar to TracerFactory to TracerProvider.

I have upcoming PRs in Meter (anotger PR is pending) , and we are likely to have lots of conflict.
