### ISSUE TITLE
[bug] Throw an exception when an unsupported counter name is created

### ISSUE THREAD

**Issue by Jebarson** [open-telemetry/opentelemetry-dotnet#5990]
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                         | 1.1.0   |
| TBD                                   | TBD     |

### Runtime Version

4.8

### Description

When a counter is created with a space within it, There are no errors thrown but the metrics just doesnt get published / exported.

### Steps to Reproduce

SomeMeter.CreateCounter<long>("Code Generated");

### Expected Result

Throws an exception when the counter is created suggesting the name is not supported.

### Actual Result

Doesn't throw an error but also does not post the metrics

**Comment by martinjt** [comment]
This is something that is part of the runtime team unfortunately, as we don't control that API.

From OpenTelemetry's perspective that is an invalid counter, but from .NET's perspective it's valid. There's not much we can do I'm afraid.

**Comment by cijothomas** [comment]
Additionally, throwing exceptions is generally not preferred/allowed in any of the APIs. It is acceptable to throw, only in the startup time (like setting up providers), but not afterwards. Since instruments can be created anytime, we won't be able to throw exceptions.

(However, I think it maybe acceptable to throw in debug mode.)

**Comment by cijothomas** [comment]
Closing this as there is no plan to make any changes in this repo. If there are other ideas/questions, feel free reopen.
