### ISSUE TITLE
Revisit TracerFactory and MeterFactory throwing when multiple calls to SetDefault

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#638]
**Is your feature request related to a problem?**
The current code throws an Exception when TracerFactory/MeterFactory.SetDefault is called more than once. Following the general rule of "telemetry libraries should never throw and continue working with defaults", this behavior need to be revisited.

**Describe the solution you'd like.**
1. Instead of throwing, simply ignore every call after the 1st call to SetDefault.
2. Log an Error level message.

**Describe alternatives you've considered.**
Let SetDefault override the previous. This leads to a last-one wins situation. 

**Additional context.**
https://github.com/open-telemetry/opentelemetry-dotnet/pull/631#discussion_r416197687
Need to see if this issue exists for other languages as well and if yes, raise this in ot-specs repo.

**Comment by longility** [comment]
Yeah, I don't think there is consistency with this one. If I read go correctly (I can't read go very well), I think it overrides the previous. For js, it keeps the first one and never override.

Personally, last one wins makes sense as the name `SetDefault` has a meaning like setter, which just sets again.

Do we want to pick a solution for now so that it is doesn't throw an exception?

**Comment by cijothomas** [comment]
Closing as this is no longer relevant. (There are other issues, but that's separately handled/tracked)
