### ISSUE TITLE
Better handling of OTLP proto sources

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet#652]
Separating this from the discussion at #19 

Currently, the proto files are copied to the OTLP exporter sources. At this stage I see two possible options:

1. Use a github submodule;
2. Hack the project to use a nuget source package - of course, in the end, this will require the proto repo to be published in a nuget.

**Comment by pcwiese** [comment]
So I've got a change that swaps out the protos with files from a git submodule but I don't know how to incorporate this into the ci workflows. A basic clone of the repo won't pull submodules by default (I think). You would need to specify the --recursive flag to the step in some way. @eddynaka Do you know offhand what additional changes would have to be done?

Here is my branch with the change:
https://github.com/pcwiese/opentelemetry-dotnet/tree/pwiese/otlp-proto-via-git-submodule

After checking this in, developers will existing repos would also have to do a:
```
git submodule init
git submodule update
```

Otherwise, the submodule files won't be there.

**Comment by eddynaka** [comment]
Talked with @pcwiese offline, but, GitHub actions does support that: https://github.com/actions/checkout

We have to add:
```
- uses: actions/checkout@v2.3.1
  with:
    submodules: 'recursive'
```

**Comment by pcwiese** [comment]
We are not going to use Git submodules for this. if we need to, we can create a NuGet package

**Comment by martinjt** [comment]
I think this is pretty solid now, and I'm not sure there are intentions to do anything else.

I'd suggest reopening this if you feel there is a need to do this with some more up to date reasoning.
