### ISSUE TITLE
Prometheus exporter not listening on all addresses

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#67]
Original: https://github.com/census-instrumentation/opencensus-csharp/issues/51

I am assuming this should work but it doesnt listen on anything related to port 9184 then, if I change it to `localhost` instead of `0.0.0.0` then it works. Is it a bug or intentional?

``` csharp
var exporter = new PrometheusExporter(
new PrometheusExporterOptions()
{
    Url = new Uri("http://0.0.0.0:9184/metrics/")
},
Stats.ViewManager);

exporter.Start();
```

**Comment by ysma500** [comment]
One of the easy solutions would be to use a `string` instead of a `Uri` in the PrometheusExporterOptions(). Then we'll be able to write the URI string as: "http://+:port/path/". Because the underlaying HttpListener() object in [MetricsHttpServer.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Exporter.Prometheus/Implementation/MetricsHttpServer.cs) can use it as prefix with "all-hosts".

**Comment by ysma500** [comment]
I'd be down to do it btw 😃 .

**Comment by SergeyKanzhelev** [comment]
great! Looking forward for your contribution.
