### ISSUE TITLE
npgsql collector

### ISSUE THREAD

**Issue by WorldIsM** [open-telemetry/opentelemetry-dotnet#698]
Hi. As far as I understand, SqlClientDiagnosticListener currently expects System.Data.SqlClient.* or Microsoft.Data.SqlClient.*.

I thought to write similar listener for npgsql, but as far as I understand npgsql driver do not produce diagnostic source events. 

Any idea what would be the approach to work with npgsql? Thanks.

**Comment by cijothomas** [comment]
In general, the libraries must emit some sort of diagnostic events so that can start collecting OTel trace/metrics from it. If the library doesn't have it, then the dotnet-autoinstrumentation efforts can help some of that.

There will be docs published in this repo on "how to instrument a library with .NET Activity API" soon.
