### ISSUE TITLE
Support gRPC client integration

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#76]
Are there plans to support tracking outgoing gRPC calls (maybe using interceptor)? Will https://github.com/grpc/grpc-dotnet help with this scenario once it is ready?

**Comment by JamesNK** [comment]
So I've been experimenting with grpc-dotnet and OpenTelemetrySDK.

Because the grpc-dotnet server is hosted on ASP.NET Core and the gRPC client uses HttpClient we get a lot of tracing for free.

![image](https://user-images.githubusercontent.com/303201/59489704-0edd2e80-8ed7-11e9-86c0-161377757c52.png)

![image](https://user-images.githubusercontent.com/303201/59489714-13094c00-8ed7-11e9-9342-10e7639907f4.png)

Source: https://github.com/JamesNK/grpc-dotnet/commit/9831bfb2d7a9b56be3c2c9e4361140b75790e926

The second screenshot shows the HTTP status code, but in gRPC it will always be 200. The gRPC status is sent as a trailer: grpc-status

I think what is needed here is a way to extend the existing ASP.NET Core and HttpClient integration and inject logic to look for that header and other gRPC specific headers, then add them to the trace.

Our tracing issue: https://github.com/grpc/grpc-dotnet/issues/318

**Comment by mdonoughe** [comment]
I think, at least with the current versions, there need to be new traces.

I'm seeing if I have an active span and then make a GRPC call, the GRPC code begins an activity before it calls HttpClient, which begins an activity before making the HTTP call. OpenTelemetry is picking up only the activity started by HttpClient and generating a span from it. Because OpenTelemetry does not generate a span from the GRPC activity, the span parent-child link is broken between the original span and the HttpClient span.

The intermediate activity is generated by Grpc.Net.Client and the event name is Grpc.Net.Client.GrpcOut.Start. The object passed along with the event appears to be the same as the one passed along with HttpRequestOut.Start.

**Comment by eddynaka** [comment]
I think that would be solved by this: https://github.com/open-telemetry/opentelemetry-dotnet/pull/687

**Comment by eddynaka** [comment]
@cijothomas , i think we can close this, since the issue #687 was closed as well.
