### ISSUE TITLE
Specifying ServiceName per Tracer or per Span

### ISSUE THREAD

**Issue by yallie** [open-telemetry/opentelemetry-dotnet#762]
Hello!

I have a monolithic application with lots of services implemented as classes, in one process.
I'd like to have all my traces attributed to their services in Jaeger UI.

As far as I see, the only way to specify a service name is to create a `TracerFactory`:

```c#
var factory = TracerFactory.Create(builder => builder.UseJaeger(o =>
{
	o.ServiceName = serviceName;
	o.AgentHost = ...
}));
```

But I'd like to avoid creating so many tracer factories.
I prefer having a single global tracer factory in my server process.
Is it possible to specify `ServiceName` for a tracer or for a telemetry span?

**Comment by ignatandrei** [comment]
For the LAST span, this can be achieved when creating an activity with ActivityKind.Client ( see  OpenTelemetry.Instrumentation.SqlClient ).

```
newAct.SetTag("peer.service", ThisAssembly.Project.AssemblyName);
newAct.SetTag("net.peer.name", ThisAssembly.Project.AssemblyName);
                 
```

But your question remains for other spans ....

**Comment by Oberon00** [comment]
I think for monitoring purposes it makes sense to view them as a single service if they run in the same process. There is no isolation between them, so if e.g. you have GC issues in one "service" the other one will be just as affected.

@ignatandrei What do you mean by "LAST span"? The peer.service attribute you mentioned is for the remote service name, not for the service name of the span. And net.peer.name is rather unrelated, it is (usually) a DNS hostname of whatever you connect to.

**Comment by ignatandrei** [comment]
@Oberon00 : 
1. For "single service "-  if you look at OpenTelemetry.Instrumentation.SqlClient ( or Http ) , you will see that they change the service name. ( the service name for Sql is the name of the SERVER  ;-) - so change if you call 2 different SqlServers)
See https://github.com/open-telemetry/opentelemetry-dotnet/blob/b021b63a2809801416b94bebdf55215ccaf06a0a/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentationOptions.cs#L226

  internal void AddConnectionLevelDetailsToActivity(string dataSource, Activity sqlActivity) 

2. For last span  - I understand application defines Service X  and if function A calls function B that call function C - and each one starts an Activity ( from ActivitySource) - the name of the service for span A and B is X and C, being last span, can set his own name of the service by setting peer.service  or net.peer.name

**Comment by tbolon** [comment]
@Oberon00 is right that the monitoring is clearly written with process boundaries (think microservices).

Clearly. in the case of a monolithic app where you want to visualize component separation you are blocked with current implementation.

My goal was to leverage the different colors used in jaeger/zipkin to identify layers in my server app, or domain boundaries, as you can see on different screenshots from jaeger UI for example :

![](https://1fykyq3mdn5r21tpna3wkdyi-wpengine.netdna-ssl.com/wp-content/uploads/2017/02/8-Screen-Shot-Trace-View.png)
![](https://logz.io/wp-content/uploads/2018/07/Jaeger-Trace-UI.png)
![](https://developers.redhat.com/blog/wp-content/uploads/2018/03/Screen-Shot-2018-03-23-at-9.39.40-AM-1024x577.png)

Currently, the UI is monochromatic for my entire server stack.

I think SQL achieve specific colors by using the ActivityKind.Client parameter, and because it involves calling an external resource.

Here, we just want to split visually the different layers of our big service.

I hoped that Activity.SetCustomProperty or Activity.SetTag could be used to override service.name. It seems not.

**Comment by tbolon** [comment]
this problem is also UI specific, see this related issue [#336 on jaeger ui project](https://github.com/jaegertracing/jaeger-ui/issues/336)

**Comment by tbolon** [comment]
See also zipkin which has the same issue: [#2512](https://github.com/openzipkin/zipkin/issues/2512)

**Comment by martinjt** [comment]
This isn't going to be possible as per the spec. A TracerProvider must provide the service as a resource attribute (not a span attribute).

You could look into multiple tracerproviders to achieve that, although it's tricky.

The better approach here is to use the OpenTelemetry Collector to do some post-processing to from a span attribute to a overwrite the resource attribute using processors, however that's not something I could go into in this ticket.
